"""Module 3 — Core Data Structures (topics 3.1 - 3.8)."""

from __future__ import annotations
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from self_created_tools.topic_builder import make_topic_data

TOPICS = [
    make_topic_data(
        topic_id="3.1",
        title="Lists",
        module=3,
        module_title="Core Data Structures",
        directory="01_lists",
        summary="Dynamic arrays, indexing, slicing, mutability, and list methods.",
        why_it_matters="Lists are the primary ordered collection structure in Python.",
        objectives=["Manipulate dynamic lists.", "Master indexing and slicing.", "Understand list memory allocation."],
        prerequisites=["Module 2 Control Flow"],
        domain="autonomous vehicle perception",
        concepts=["List", "Slicing", "Mutability"],
        code_snippets={
            "syntax": "items = [1, 2, 3]\nitems.append(4)",
            "basic": "colors = ['red', 'green', 'blue']\nprint(colors[0])",
            "intermediate": "nums = [0, 1, 2, 3, 4, 5]\nsub = nums[1:4]",
            "advanced": "lst = [1, 2, 3]\nlst[1:2] = [10, 20]\nprint(lst)",
            "walkthrough": "data = [10, 20, 30]\ndata.extend([40, 50])\npopped = data.pop()",
            "pythonic": "rev = items[::-1]",
            "engineering": "def filter_sensor_batch(readings, min_v, max_v):\n    return [r for r in readings if min_v <= r <= max_v]",
            "m1_code": "def solve_m1(lst):\n    return lst[::-1]",
            "m1_test": "assert solve_m1([1, 2, 3]) == [3, 2, 1]",
            "m2_code": "def solve_m2(lst):\n    return sum(lst) / len(lst) if lst else 0.0",
            "m2_test": "assert solve_m2([10, 20]) == 15.0",
            "m3_code": "def solve_m3(lst, val):\n    return [x for x in lst if x != val]",
            "m3_test": "assert solve_m3([1, 2, 1], 1) == [2]",
            "m4_code": "def solve_m4(l1, l2):\n    return l1 + l2",
            "m4_test": "assert solve_m4([1], [2]) == [1, 2]",
            "m5_code": "def solve_m5(lst):\n    return [lst[0], lst[-1]] if lst else []",
            "m5_test": "assert solve_m5([10, 20, 30]) == [10, 30]",
            "h1_code": "def solve_h1(lst):\n    seen = set()\n    res = []\n    for x in lst:\n        if x not in seen:\n            seen.add(x)\n            res.append(x)\n    return res",
            "h1_test": "assert solve_h1([1, 2, 1, 3]) == [1, 2, 3]",
            "h2_code": "def solve_h2(lst, k):\n    if not lst: return lst\n    k = k % len(lst)\n    return lst[-k:] + lst[:-k]",
            "h2_test": "assert solve_h2([1, 2, 3, 4], 1) == [4, 1, 2, 3]",
            "h3_code": "def solve_h3(nested):\n    res = []\n    def flat(items):\n        for x in items:\n            if isinstance(x, list):\n                flat(x)\n            else:\n                res.append(x)\n    flat(nested)\n    return res",
            "h3_test": "assert solve_h3([1, [2, [3]]]) == [1, 2, 3]",
            "h4_code": "def solve_h4(lst, chunk_size):\n    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]",
            "h4_test": "assert solve_h4([1, 2, 3, 4, 5], 2) == [[1, 2], [3, 4], [5]]",
            "h5_code": "def solve_h5(l1, l2):\n    i, j = 0, 0\n    merged = []\n    while i < len(l1) and j < len(l2):\n        if l1[i] <= l2[j]:\n            merged.append(l1[i])\n            i += 1\n        else:\n            merged.append(l2[j])\n            j += 1\n    merged.extend(l1[i:])\n    merged.extend(l2[j:])\n    return merged",
            "h5_test": "assert solve_h5([1, 3], [2, 4]) == [1, 2, 3, 4]",
            "rob_code": "def process_telemetry(data):\n    return {'clean_data': [x for x in data if x > 0]}",
            "rob_test": "assert process_telemetry([1.0, -0.5, 2.0])['clean_data'] == [1.0, 2.0]"
        }
    ),
    make_topic_data(
        topic_id="3.2",
        title="Tuples",
        module=3,
        module_title="Core Data Structures",
        directory="02_tuples",
        summary="Immutable sequences, tuple unpacking, and records.",
        why_it_matters="Tuples provide immutable sequence guarantees and efficient fixed structure memory layout.",
        objectives=["Work with immutable tuples.", "Master tuple unpacking.", "Use tuples as dictionary keys."],
        prerequisites=["Topic 3.1 Lists"],
        domain="autonomous vehicle perception",
        concepts=["Tuple", "Immutability", "Unpacking"],
        code_snippets={
            "syntax": "point = (10.0, 20.0)",
            "basic": "x, y = point\nprint(x, y)",
            "intermediate": "def get_coords():\n    return (12.3, 45.6)\nlat, lon = get_coords()",
            "advanced": "t = (1, [2, 3])\nt[1].append(4)  # Mutating mutable object inside tuple",
            "walkthrough": "waypoint = (12.5, 30.1, 5.0)\nx, y, z = waypoint\nprint(f'Pos: x={x}, y={y}, z={z}')",
            "pythonic": "a, b, *rest = (1, 2, 3, 4, 5)",
            "engineering": "def calc_centroid(points):\n    n = len(points)\n    sum_x = sum(p[0] for p in points)\n    sum_y = sum(p[1] for p in points)\n    return (sum_x / n, sum_y / n)",
            "m1_code": "def solve_m1(tup):\n    return tup[::-1]",
            "m1_test": "assert solve_m1((1, 2, 3)) == (3, 2, 1)",
            "m2_code": "def solve_m2(a, b):\n    return (a, b), (b, a)",
            "m2_test": "assert solve_m2(1, 2) == ((1, 2), (2, 1))",
            "m3_code": "def solve_m3(tup):\n    return (tup[0], tup[-1])",
            "m3_test": "assert solve_m3((10, 20, 30)) == (10, 30)",
            "m4_code": "def solve_m4(tuples_list):\n    return sorted(tuples_list, key=lambda x: x[1])",
            "m4_test": "assert solve_m4([(1, 3), (2, 1)]) == [(2, 1), (1, 3)]",
            "m5_code": "def solve_m5(tup):\n    return len(tup)",
            "m5_test": "assert solve_m5((1, 2, 3)) == 3",
            "h1_code": "def solve_h1(p1, p2):\n    return ((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)**0.5",
            "h1_test": "assert solve_h1((0, 0), (3, 4)) == 5.0",
            "h2_code": "def solve_h2(tup):\n    return hash(tup)",
            "h2_test": "assert isinstance(solve_h2((1, 2)), int)",
            "h3_code": "def solve_h3(tuples_list):\n    return [t for t in tuples_list if len(t) == 2]",
            "h3_test": "assert solve_h3([(1, 2), (1, 2, 3)]) == [(1, 2)]",
            "h4_code": "def solve_h4(tup):\n    res = []\n    for item in tup:\n        if isinstance(item, tuple):\n            res.extend(solve_h4(item))\n        else:\n            res.append(item)\n    return tuple(res)",
            "h4_test": "assert solve_h4((1, (2, (3, 4)))) == (1, 2, 3, 4)",
            "h5_code": "def solve_h5(tuples_list):\n    d = {}\n    for k, v in tuples_list:\n        d.setdefault(k, []).append(v)\n    return d",
            "h5_test": "assert solve_h5([('a', 1), ('a', 2)]) == {'a': [1, 2]}",
            "rob_code": "def process_telemetry(data):\n    pose = (data[0], data[1]) if len(data) >= 2 else (0.0, 0.0)\n    return {'pose': pose}",
            "rob_test": "assert process_telemetry([1.5, 2.5])['pose'] == (1.5, 2.5)"
        }
    ),
    make_topic_data(
        topic_id="3.3",
        title="Sets",
        module=3,
        module_title="Core Data Structures",
        directory="03_sets",
        summary="Unordered collections of unique hashable elements and set operations.",
        why_it_matters="Sets provide O(1) membership testing and set-theoretic mathematical operations.",
        objectives=["Perform union, intersection, difference.", "Deduplicate data structures efficiently.", "Understand set hashing."],
        prerequisites=["Topic 3.2 Tuples"],
        domain="autonomous vehicle perception",
        concepts=["Set", "Uniqueness", "Set Operations"],
        code_snippets={
            "syntax": "s = {1, 2, 3}\ns.add(4)",
            "basic": "a = {1, 2}\nb = {2, 3}\nprint(a | b)",
            "intermediate": "unique_ids = set([101, 102, 101, 103])",
            "advanced": "frozen = frozenset([1, 2, 3])",
            "walkthrough": "s1 = {'sensor_a', 'sensor_b'}\ns2 = {'sensor_b', 'sensor_c'}\ncommon = s1 & s2\nprint('Common:', common)",
            "pythonic": "diff = s1 - s2",
            "engineering": "def active_node_diff(target_nodes, current_nodes):\n    return target_nodes.difference(current_nodes)",
            "m1_code": "def solve_m1(lst):\n    return list(set(lst))",
            "m1_test": "assert sorted(solve_m1([1, 2, 1, 3])) == [1, 2, 3]",
            "m2_code": "def solve_m2(s1, s2):\n    return s1 & s2",
            "m2_test": "assert solve_m2({1, 2}, {2, 3}) == {2}",
            "m3_code": "def solve_m3(s1, s2):\n    return s1 | s2",
            "m3_test": "assert solve_m3({1}, {2}) == {1, 2}",
            "m4_code": "def solve_m4(s1, s2):\n    return s1 - s2",
            "m4_test": "assert solve_m4({1, 2}, {2}) == {1}",
            "m5_code": "def solve_m5(s1, s2):\n    return s1.issubset(s2)",
            "m5_test": "assert solve_m5({1}, {1, 2}) is True",
            "h1_code": "def solve_h1(s1, s2):\n    return s1 ^ s2",
            "h1_test": "assert solve_h1({1, 2}, {2, 3}) == {1, 3}",
            "h2_code": "def solve_h2(sets_list):\n    if not sets_list: return set()\n    res = sets_list[0].copy()\n    for s in sets_list[1:]:\n        res &= s\n    return res",
            "h2_test": "assert solve_h2([{1, 2}, {2, 3}, {2, 4}]) == {2}",
            "h3_code": "def solve_h3(str1, str2):\n    return set(str1) == set(str2)",
            "h3_test": "assert solve_h3('listen', 'silent') is True",
            "h4_code": "def solve_h4(items):\n    return frozenset(items)",
            "h4_test": "assert isinstance(solve_h4([1, 2]), frozenset)",
            "h5_code": "def solve_h5(lst1, lst2):\n    return len(set(lst1) & set(lst2))",
            "h5_test": "assert solve_h5([1, 2, 3], [2, 3, 4]) == 2",
            "rob_code": "def process_telemetry(data):\n    unique_codes = set(data)\n    return {'unique_count': len(unique_codes)}",
            "rob_test": "assert process_telemetry(['E1', 'E2', 'E1'])['unique_count'] == 2"
        }
    ),
    make_topic_data(
        topic_id="3.4",
        title="Dictionaries",
        module=3,
        module_title="Core Data Structures",
        directory="04_dictionaries",
        summary="Key-value mapping data structures, dict methods, and hash maps.",
        why_it_matters="Dictionaries enable efficient key-based lookup for state management and configuration.",
        objectives=["Work with key-value pairs.", "Use dict methods safely.", "Understand dictionary key immutability."],
        prerequisites=["Topic 3.3 Sets"],
        domain="port crane telemetry",
        concepts=["Dictionary", "Key-Value", "Hash Table"],
        code_snippets={
            "syntax": "d = {'key': 'value'}\nd['key2'] = 'value2'",
            "basic": "config = {'port': 8080, 'host': 'localhost'}\nprint(config.get('port'))",
            "intermediate": "for k, v in config.items():\n    print(k, v)",
            "advanced": "d = {x: x**2 for x in range(5)}",
            "walkthrough": "state = {'x': 1.0, 'y': 2.0}\nstate['battery'] = 98.5\nprint(f'Battery: {state.get(\"battery\", 0.0)}%')",
            "pythonic": "val = d.setdefault('counter', 0)",
            "engineering": "def update_telemetry(state_dict, new_readings):\n    state_dict.update(new_readings)\n    return state_dict",
            "m1_code": "def solve_m1(d, key, default_val):\n    return d.get(key, default_val)",
            "m1_test": "assert solve_m1({'a': 1}, 'b', 0) == 0",
            "m2_code": "def solve_m2(d1, d2):\n    res = d1.copy()\n    res.update(d2)\n    return res",
            "m2_test": "assert solve_m2({'a': 1}, {'b': 2}) == {'a': 1, 'b': 2}",
            "m3_code": "def solve_m3(d):\n    return {v: k for k, v in d.items()}",
            "m3_test": "assert solve_m3({'a': 1}) == {1: 'a'}",
            "m4_code": "def solve_m4(keys, default_value):\n    return dict.fromkeys(keys, default_value)",
            "m4_test": "assert solve_m4(['a', 'b'], 0) == {'a': 0, 'b': 0}",
            "m5_code": "def solve_m5(d):\n    return sorted(d.keys())",
            "m5_test": "assert solve_m5({'b': 1, 'a': 2}) == ['a', 'b']",
            "h1_code": "def solve_h1(d):\n    res = {}\n    def recurse(curr, prefix=''):\n        for k, v in curr.items():\n            key = f'{prefix}.{k}' if prefix else k\n            if isinstance(v, dict):\n                recurse(v, key)\n            else:\n                res[key] = v\n    recurse(d)\n    return res",
            "h1_test": "assert solve_h1({'a': {'b': 1}}) == {'a.b': 1}",
            "h2_code": "def solve_h2(d):\n    return dict(sorted(d.items(), key=lambda item: item[1]))",
            "h2_test": "assert list(solve_h2({'a': 10, 'b': 5}).keys()) == ['b', 'a']",
            "h3_code": "def solve_h3(dict_list, key):\n    groups = {}\n    for d in dict_list:\n        val = d.get(key)\n        groups.setdefault(val, []).append(d)\n    return groups",
            "h3_test": "assert len(solve_h3([{'type': 'A', 'val': 1}], 'type')['A']) == 1",
            "h4_code": "def solve_h4(d1, d2):\n    res = d1.copy()\n    for k, v in d2.items():\n        if k in res and isinstance(res[k], int) and isinstance(v, int):\n            res[k] += v\n        else:\n            res[k] = v\n    return res",
            "h4_test": "assert solve_h4({'a': 1}, {'a': 2, 'b': 3}) == {'a': 3, 'b': 3}",
            "h5_code": "def solve_h5(keys, values):\n    return {k: v for k, v in zip(keys, values)}",
            "h5_test": "assert solve_h5(['x', 'y'], [1, 2]) == {'x': 1, 'y': 2}",
            "rob_code": "def process_telemetry(data):\n    state = {'sensor_count': len(data), 'active': True}\n    return state",
            "rob_test": "assert process_telemetry([1, 2])['sensor_count'] == 2"
        }
    ),
    make_topic_data(
        topic_id="3.5",
        title="Strings and Advanced String Manipulation",
        module=3,
        module_title="Core Data Structures",
        directory="05_strings_advanced_manipulation",
        summary="String immutability, formatting, splitting, joining, and regex fundamentals.",
        why_it_matters="Strings process text protocols, logs, serializations, and command inputs.",
        objectives=["Master string slicing and splitting.", "Parse structured log lines.", "Format strings efficiently."],
        prerequisites=["Topic 3.4 Dictionaries"],
        domain="port crane telemetry",
        concepts=["Strings", "Immutability", "Log Parsing"],
        code_snippets={
            "syntax": "s = 'hello world'\nparts = s.split()",
            "basic": "joined = ', '.join(['a', 'b', 'c'])",
            "intermediate": "text = '  ROBOT_01: OK  '\ncleaned = text.strip().replace('ROBOT_', '')",
            "advanced": "raw = 'x=10;y=20'\nparsed = dict(item.split('=') for item in raw.split(';'))",
            "walkthrough": "line = '2026-10-03 INFO Robot ready'\ntokens = line.split()\nlog_level = tokens[1]\nprint('Log level:', log_level)",
            "pythonic": "is_valid = text.isalnum()",
            "engineering": "def parse_nmea_sentence(sentence):\n    if not sentence.startswith('$'): return None\n    parts = sentence[1:].split('*')[0].split(',')\n    return {'cmd': parts[0], 'args': parts[1:]}",
            "m1_code": "def solve_m1(s):\n    return s[::-1]",
            "m1_test": "assert solve_m1('python') == 'nohtyp'",
            "m2_code": "def solve_m2(s):\n    return ' '.join(s.split())",
            "m2_test": "assert solve_m2('  hello   world  ') == 'hello world'",
            "m3_code": "def solve_m3(s, prefix):\n    return s.startswith(prefix)",
            "m3_test": "assert solve_m3('robotics', 'ro') is True",
            "m4_code": "def solve_m4(s):\n    return s.count('a') + s.count('A')",
            "m4_test": "assert solve_m4('Alpha') == 2",
            "m5_code": "def solve_m5(csv_line):\n    return [item.strip() for item in csv_line.split(',')]",
            "m5_test": "assert solve_m5('a, b , c') == ['a', 'b', 'c']",
            "h1_code": "def solve_h1(s):\n    words = s.split()\n    return ' '.join(word.capitalize() for word in words)",
            "h1_test": "assert solve_h1('python master course') == 'Python Master Course'",
            "h2_code": "def solve_h2(s):\n    freq = {}\n    for char in s:\n        freq[char] = freq.get(char, 0) + 1
    return freq",
            "h2_test": "assert solve_h2('aba')['a'] == 2",
            "h3_code": "def solve_h3(log_str):\n    import re\n    return re.findall(r'\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b', log_str)",
            "h3_test": "assert solve_h3('IP is 192.168.1.1 here') == ['192.168.1.1']",
            "h4_code": "def solve_h4(s):\n    res = []\n    for char in s:\n        if char.isupper():\n            res.append(char.lower())\n        else:\n            res.append(char.upper())\n    return ''.join(res)",
            "h4_test": "assert solve_h4('PyThOn') == 'pYtHoN'",
            "h5_code": "def solve_h5(s):\n    cleaned = ''.join(c.lower() for c in s if c.isalnum())\n    return cleaned == cleaned[::-1]",
            "h5_test": "assert solve_h5('A man, a plan, a canal: Panama') is True",
            "rob_code": "def process_telemetry(data):\n    msg = str(data[0]) if data else ''\n    return {'clean_msg': msg.upper().strip()}",
            "rob_test": "assert process_telemetry(['  status_ok '])['clean_msg'] == 'STATUS_OK'"
        }
    ),
    make_topic_data(
        topic_id="3.6",
        title="Looping Through Data Structures",
        module=3,
        module_title="Core Data Structures",
        directory="06_looping_data_structures",
        summary="Iterating over lists, dicts, sets, tuples, and nested structures.",
        why_it_matters="Selecting the correct iteration pattern prevents bugs and optimizes runtime.",
        objectives=["Iterate over dict items.", "Safely mutate structures during iteration.", "Process nested collections."],
        prerequisites=["Topic 3.5 Strings"],
        domain="cleanroom material handler",
        concepts=["Iteration Patterns", "Nested Iteration"],
        code_snippets={
            "syntax": "for k, v in d.items():\n    print(k, v)",
            "basic": "for i in range(len(lst)):\n    print(lst[i])",
            "intermediate": "for key in list(d.keys()):\n    if d[key] < 0:\n        del d[key]",
            "advanced": "def walk_nested(container):\n    if isinstance(container, dict):\n        for k, v in container.items():\n            yield k, v\n            yield from walk_nested(v)",
            "walkthrough": "fleet = [{'id': 'R1', 'ok': True}, {'id': 'R2', 'ok': False}]\nfor r in fleet:\n    if not r['ok']:\n        print(f'Robot {r[\"id\"]} fault')",
            "pythonic": "valid = [v for k, v in d.items() if v is not None]",
            "engineering": "def audit_fleet_telemetry(telemetry_map):\n    faulty = []\n    for robot_id, sensors in telemetry_map.items():\n        if any(v < 0 for v in sensors.values()):\n            faulty.append(robot_id)\n    return faulty",
            "m1_code": "def solve_m1(d):\n    return sum(d.values())",
            "m1_test": "assert solve_m1({'a': 10, 'b': 20}) == 30",
            "m2_code": "def solve_m2(lst):\n    return [x for x in lst if x > 0]",
            "m2_test": "assert solve_m2([-1, 2, -3, 4]) == [2, 4]",
            "m3_code": "def solve_m3(d):\n    return {k: v for k, v in d.items() if v % 2 == 0}",
            "m3_test": "assert solve_m3({'a': 1, 'b': 2}) == {'b': 2}",
            "m4_code": "def solve_m4(list_of_dicts):\n    return [d['name'] for d in list_of_dicts if 'name' in d]",
            "m4_test": "assert solve_m4([{'name': 'A'}, {}]) == ['A']",
            "m5_code": "def solve_m5(tuples_list):\n    return sum(x * y for x, y in tuples_list)",
            "m5_test": "assert solve_m5([(1, 2), (3, 4)]) == 14",
            "h1_code": "def solve_h1(d):\n    res = {}\n    for k, v in d.items():\n        if v not in res:\n            res[v] = []\n        res[v].append(k)\n    return res",
            "h1_test": "assert solve_h1({'a': 1, 'b': 1}) == {1: ['a', 'b']}",
            "h2_code": "def solve_h2(nested_list):\n    res = []\n    for sub in nested_list:\n        for item in sub:\n            res.append(item)\n    return res",
            "h2_test": "assert solve_h2([[1], [2, 3]]) == [1, 2, 3]",
            "h3_code": "def solve_h3(d):\n    return {k: v for k, v in d.items() if v is not None}",
            "h3_test": "assert solve_h3({'a': 1, 'b': None}) == {'a': 1}",
            "h4_code": "def solve_h4(d, target_val):\n    return [k for k, v in d.items() if v == target_val]",
            "h4_test": "assert solve_h4({'a': 1, 'b': 1, 'c': 2}, 1) == ['a', 'b']",
            "h5_code": "def solve_h5(records):\n    res = {}\n    for r in records:\n        cat = r['cat']\n        val = r['val']\n        res[cat] = res.get(cat, 0) + val\n    return res",
            "h5_test": "assert solve_h5([{'cat': 'A', 'val': 10}, {'cat': 'A', 'val': 5}]) == {'A': 15}",
            "rob_code": "def process_telemetry(data):\n    count = sum(1 for x in data if x > 0)\n    return {'positive_readings': count}",
            "rob_test": "assert process_telemetry([1.0, -1.0, 2.0])['positive_readings'] == 2"
        }
    ),
    make_topic_data(
        topic_id="3.7",
        title="Comprehensions",
        module=3,
        module_title="Core Data Structures",
        directory="07_comprehensions",
        summary="List, dict, set, and generator comprehensions.",
        why_it_matters="Comprehensions provide concise, highly optimized syntax for transforming collections.",
        objectives=["Write list comprehensions with filters.", "Construct dict and set comprehensions.", "Understand generator expressions."],
        prerequisites=["Topic 3.6 Looping"],
        domain="cleanroom material handler",
        concepts=["Comprehensions", "Generator Expressions"],
        code_snippets={
            "syntax": "squares = [x**2 for x in range(5)]",
            "basic": "evens = [x for x in range(10) if x % 2 == 0]",
            "intermediate": "sq_map = {x: x**2 for x in range(5)}",
            "advanced": "matrix = [[r*2 + c for c in range(2)] for r in range(2)]",
            "walkthrough": "temps = [20.5, 22.1, 19.8]\nfahrenheit = [t * 9/5 + 32 for t in temps]\nprint('Fahrenheit:', fahrenheit)",
            "pythonic": "gen = (x**2 for x in range(1000))  # Generator expression",
            "engineering": "def filter_and_scale(signals, factor, min_val):\n    return [s * factor for s in signals if s >= min_val]",
            "m1_code": "def solve_m1(n):\n    return [x**2 for x in range(n)]",
            "m1_test": "assert solve_m1(4) == [0, 1, 4, 9]",
            "m2_code": "def solve_m2(words):\n    return [len(w) for w in words]",
            "m2_test": "assert solve_m2(['a', 'bc']) == [1, 2]",
            "m3_code": "def solve_m3(keys, vals):\n    return {k: v for k, v in zip(keys, vals)}",
            "m3_test": "assert solve_m3(['a'], [1]) == {'a': 1}",
            "m4_code": "def solve_m4(words):\n    return {w[0].upper() for w in words if w}",
            "m4_test": "assert solve_m4(['apple', 'banana', 'apricot']) == {'A', 'B'}",
            "m5_code": "def solve_m5(matrix):\n    return [val for row in matrix for val in row]",
            "m5_test": "assert solve_m5([[1], [2, 3]]) == [1, 2, 3]",
            "h1_code": "def solve_h1(n):\n    return [x for x in range(2, n) if all(x % d != 0 for d in range(2, int(x**0.5) + 1))]",
            "h1_test": "assert solve_h1(10) == [2, 3, 5, 7]",
            "h2_code": "def solve_h2(d):\n    return {k: v for k, v in d.items() if v > 0}",
            "h2_test": "assert solve_h2({'a': 1, 'b': -1}) == {'a': 1}",
            "h3_code": "def solve_h3(rows, cols):\n    return [[0 if r != c else 1 for c in range(cols)] for r in range(rows)]",
            "h3_test": "assert solve_h3(2, 2) == [[1, 0], [0, 1]]",
            "h4_code": "def solve_h4(words):\n    return {w: len(w) for w in words}",
            "h4_test": "assert solve_h4(['cat']) == {'cat': 3}",
            "h5_code": "def solve_h5(gen_expr):\n    return sum(gen_expr)",
            "h5_test": "assert solve_h5(x for x in range(5)) == 10",
            "rob_code": "def process_telemetry(data):\n    scaled = [x * 100.0 for x in data if x >= 0]\n    return {'scaled': scaled}",
            "rob_test": "assert process_telemetry([0.1, -0.5, 0.2])['scaled'] == [10.0, 20.0]"
        }
    ),
    make_topic_data(
        topic_id="3.8",
        title="collections Module",
        module=3,
        module_title="Core Data Structures",
        directory="08_collections_module",
        summary="Counter, defaultdict, namedtuple, and deque from standard collections.",
        why_it_matters="Standard collections extend basic structures with optimized data abstractions.",
        objectives=["Count elements with Counter.", "Handle missing keys with defaultdict.", "Use deque for FIFO queues."],
        prerequisites=["Topic 3.7 Comprehensions"],
        domain="cleanroom material handler",
        concepts=["Counter", "defaultdict", "namedtuple", "deque"],
        code_snippets={
            "syntax": "from collections import Counter, defaultdict, namedtuple, deque\ncounts = Counter([1, 1, 2])",
            "basic": "Point = namedtuple('Point', ['x', 'y'])\np = Point(1.0, 2.0)\nprint(p.x, p.y)",
            "intermediate": "d = defaultdict(list)\nd['sensors'].append('lidar')",
            "advanced": "q = deque(maxlen=3)\nfor i in range(5):\n    q.append(i)\nprint(list(q))",
            "walkthrough": "from collections import Counter\nevents = ['START', 'RUN', 'RUN', 'STOP']\nfreq = Counter(events)\nprint('Run count:', freq['RUN'])",
            "pythonic": "from collections import deque\nbuffer = deque([1, 2, 3], maxlen=10)",
            "engineering": "from collections import deque, defaultdict\nclass RingBuffer:\n    def __init__(self, size):\n        self.buf = deque(maxlen=size)\n    def add(self, item):\n        self.buf.append(item)",
            "m1_code": "def solve_m1(items):\n    from collections import Counter\n    return dict(Counter(items))",
            "m1_test": "assert solve_m1(['a', 'a', 'b']) == {'a': 2, 'b': 1}",
            "m2_code": "def solve_m2(pairs):\n    from collections import defaultdict\n    d = defaultdict(list)\n    for k, v in pairs:\n        d[k].append(v)\n    return dict(d)",
            "m2_test": "assert solve_m2([('a', 1), ('a', 2)]) == {'a': [1, 2]}",
            "m3_code": "def solve_m3(x, y):\n    from collections import namedtuple\n    Point = namedtuple('Point', ['x', 'y'])\n    p = Point(x, y)\n    return p.x, p.y",
            "m3_test": "assert solve_m3(10, 20) == (10, 20)",
            "m4_code": "def solve_m4(items, maxlen):\n    from collections import deque\n    return list(deque(items, maxlen=maxlen))",
            "m4_test": "assert solve_m4([1, 2, 3, 4], 2) == [3, 4]",
            "m5_code": "def solve_m5(items, k):\n    from collections import Counter\n    return Counter(items).most_common(k)",
            "m5_test": "assert solve_m5(['a', 'a', 'b'], 1) == [('a', 2)]",
            "h1_code": "def solve_h1(s1, s2):\n    from collections import Counter\n    return Counter(s1) == Counter(s2)",
            "h1_test": "assert solve_h1('listen', 'silent') is True",
            "h2_code": "def solve_h2(d1, d2):\n    from collections import ChainMap\n    return dict(ChainMap(d1, d2))",
            "h2_test": "assert solve_h2({'a': 1}, {'b': 2}) in [{'a': 1, 'b': 2}, {'b': 2, 'a': 1}]",
            "h3_code": "def solve_h3(items):\n    from collections import OrderedDict\n    return list(OrderedDict.fromkeys(items))",
            "h3_test": "assert solve_h3([1, 2, 1, 3]) == [1, 2, 3]",
            "h4_code": "def solve_h4(q_items, n):\n    from collections import deque\n    d = deque(q_items)\n    d.rotate(n)\n    return list(d)",
            "h4_test": "assert solve_h4([1, 2, 3], 1) == [3, 1, 2]",
            "h5_code": "def solve_h5(records):\n    from collections import defaultdict\n    counts = defaultdict(int)\n    for r in records:\n        counts[r['status']] += 1\n    return dict(counts)",
            "h5_test": "assert solve_h5([{'status': 'OK'}, {'status': 'OK'}]) == {'OK': 2}",
            "rob_code": "def process_telemetry(data):\n    from collections import deque\n    recent = deque(data, maxlen=3)\n    return {'ring_buffer': list(recent)}",
            "rob_test": "assert process_telemetry([1, 2, 3, 4])['ring_buffer'] == [2, 3, 4]"
        }
    )
]
