"""Module 8 — Databases (topics 8.1 - 8.8)."""

from __future__ import annotations
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from self_created_tools.topic_builder import make_topic_data

TOPICS = [
    make_topic_data(
        topic_id="8.1", title="Introduction to Databases", module=8, module_title="Databases",
        directory="01_intro_to_databases", summary="Relational databases, SQL fundamentals, and database design.",
        why_it_matters="Databases provide persistent, transactional, and queryable state storage for fleet operations.",
        objectives=["Understand relational database concepts.", "Write basic SQL SELECT queries.", "Design relational schema."],
        prerequisites=["Module 7 Working with Data"], domain="fleet operations centre", concepts=["Databases", "SQL", "Relational Model"],
        code_snippets={
            "syntax": "# SQL Syntax Example:\n# SELECT * FROM robots WHERE status = 'ACTIVE';", "basic": "query = 'SELECT id, battery FROM fleet;'",
            "intermediate": "schema = '''\nCREATE TABLE fleet (\n    id INTEGER PRIMARY KEY,\n    name TEXT NOT NULL\n);\n'''",
            "advanced": "query = '''\nSELECT fleet.name, AVG(telemetry.val)\nFROM fleet JOIN telemetry ON fleet.id = telemetry.robot_id\nGROUP BY fleet.name;\n'''",
            "walkthrough": "query = 'SELECT * FROM robots WHERE battery_pct > 20.0'\nprint('SQL Query:', query)",
            "pythonic": "query = 'SELECT id FROM fleet WHERE status = ?'", "engineering": "def build_fleet_query(min_battery, active_only=True):\n    conditions = [f'battery_pct >= {min_battery}']\n    if active_only:\n        conditions.append(\"status = 'ACTIVE'\")\n    return f'SELECT * FROM fleet WHERE {\" AND \".join(conditions)};'",
            "m1_code": "def solve_m1(table_name):\n    return f'SELECT * FROM {table_name};'", "m1_test": "assert solve_m1('robots') == 'SELECT * FROM robots;'",
            "m2_code": "def solve_m2(table, col, val):\n    return f'SELECT * FROM {table} WHERE {col} = {val};'", "m2_test": "assert solve_m2('fleet', 'id', 1) == 'SELECT * FROM fleet WHERE id = 1;'",
            "m3_code": "def solve_m3(table, col):\n    return f'SELECT COUNT({col}) FROM {table};'", "m3_test": "assert solve_m3('logs', 'id') == 'SELECT COUNT(id) FROM logs;'",
            "m4_code": "def solve_m4(table, col):\n    return f'SELECT * FROM {table} ORDER BY {col} DESC;'", "m4_test": "assert solve_m4('fleet', 'speed') == 'SELECT * FROM fleet ORDER BY speed DESC;'",
            "m5_code": "def solve_m5(table, limit):\n    return f'SELECT * FROM {table} LIMIT {limit};'", "m5_test": "assert solve_m5('fleet', 5) == 'SELECT * FROM fleet LIMIT 5;'",
            "h1_code": "def solve_h1(t1, t2, fk, pk):\n    return f'SELECT * FROM {t1} JOIN {t2} ON {t1}.{fk} = {t2}.{pk};'", "h1_test": "assert 'JOIN' in solve_h1('a', 'b', 'b_id', 'id')",
            "h2_code": "def solve_h2(table, group_col, agg_col):\n    return f'SELECT {group_col}, AVG({agg_col}) FROM {table} GROUP BY {group_col};'", "h2_test": "assert 'GROUP BY' in solve_h2('fleet', 'type', 'battery')",
            "h3_code": "def solve_h3(table, col, vals):\n    val_str = ', '.join(f\"'{v}'\" if isinstance(v, str) else str(v) for v in vals)\n    return f'SELECT * FROM {table} WHERE {col} IN ({val_str});'", "h3_test": "assert \"IN ('A', 'B')\" in solve_h3('f', 'type', ['A', 'B'])",
            "h4_code": "def solve_h4(table, col, min_v, max_v):\n    return f'SELECT * FROM {table} WHERE {col} BETWEEN {min_v} AND {max_v};'", "h4_test": "assert 'BETWEEN 10 AND 20' in solve_h4('fleet', 'battery', 10, 20)",
            "h5_code": "def solve_h5(table, col):\n    return f'SELECT DISTINCT {col} FROM {table};'", "h5_test": "assert solve_h5('fleet', 'status') == 'SELECT DISTINCT status FROM fleet;'",
            "rob_code": "def process_telemetry(data):\n    query = f'SELECT * FROM telemetry WHERE id IN ({len(data)});'\n    return {'query': query}", "rob_test": "assert 'SELECT' in process_telemetry([1])['query']"
        }
    ),
    make_topic_data(
        topic_id="8.2", title="SQLite", module=8, module_title="Databases",
        directory="02_sqlite", summary="sqlite3 module, in-memory databases, and file-backed SQLite.",
        why_it_matters="SQLite provides zero-configuration, serverless, self-contained SQL storage.",
        objectives=["Connect to SQLite using sqlite3.", "Execute DDL statements.", "Use in-memory sqlite3 databases."],
        prerequisites=["Topic 8.1 Intro to Databases"], domain="fleet operations centre", concepts=["SQLite", "sqlite3", "In-Memory Database"],
        code_snippets={
            "syntax": "import sqlite3\nconn = sqlite3.connect(':memory:')", "basic": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (id INT);')",
            "intermediate": "import sqlite3\nconn = sqlite3.connect(':memory:')\ncur = conn.cursor()\ncur.execute('CREATE TABLE t (x INT);')\ncur.execute('INSERT INTO t VALUES (1);')\nconn.commit()", "advanced": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.row_factory = sqlite3.Row",
            "walkthrough": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE fleet (name TEXT, battery REAL)')\nconn.execute(\"INSERT INTO fleet VALUES ('ROBO-1', 95.0)\")\nconn.commit()\nrow = conn.execute('SELECT * FROM fleet').fetchone()\nprint('Fleet record:', dict(row) if hasattr(row, 'keys') else row)",
            "pythonic": "with sqlite3.connect(':memory:') as conn:\n    conn.execute('CREATE TABLE t (id INT)')", "engineering": "import sqlite3\ndef init_robot_db(db_path=':memory:'):\n    conn = sqlite3.connect(db_path)\n    conn.row_factory = sqlite3.Row\n    conn.execute('''\n        CREATE TABLE IF NOT EXISTS telemetry (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            robot_id TEXT NOT NULL,\n            voltage REAL NOT NULL\n        )\n    ''')\n    conn.commit()\n    return conn",
            "m1_code": "def solve_m1():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    return conn is not None", "m1_test": "assert solve_m1() is True",
            "m2_code": "def solve_m2():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT);')\n    return True", "m2_test": "assert solve_m2() is True",
            "m3_code": "def solve_m3(val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (val INT);')\n    conn.execute('INSERT INTO t VALUES (?);', (val,))\n    conn.commit()\n    res = conn.execute('SELECT val FROM t;').fetchone()[0]\n    return res", "m3_test": "assert solve_m3(42) == 42",
            "m4_code": "def solve_m4(vals):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (val INT);')\n    conn.executemany('INSERT INTO t VALUES (?);', [(v,) for v in vals])\n    conn.commit()\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m4_test": "assert solve_m4([1, 2, 3]) == 3",
            "m5_code": "def solve_m5():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.row_factory = sqlite3.Row\n    conn.execute('CREATE TABLE t (a INT, b TEXT);')\n    conn.execute(\"INSERT INTO t VALUES (1, 'x');\")\n    row = conn.execute('SELECT * FROM t;').fetchone()\n    return row['a'], row['b']", "m5_test": "assert solve_m5() == (1, 'x')",
            "h1_code": "def solve_h1(records):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE r (name TEXT, score REAL);')\n    conn.executemany('INSERT INTO r VALUES (?, ?);', records)\n    conn.commit()\n    return conn.execute('SELECT AVG(score) FROM r;').fetchone()[0]", "h1_test": "assert solve_h1([('a', 10.0), ('b', 20.0)]) == 15.0",
            "h2_code": "def solve_h2(data_dict):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE config (key TEXT PRIMARY KEY, val TEXT);')\n    conn.executemany('INSERT INTO config VALUES (?, ?);', list(data_dict.items()))\n    conn.commit()\n    return dict(conn.execute('SELECT key, val FROM config;').fetchall())", "h2_test": "assert solve_h2({'port': '8080'}) == {'port': '8080'}",
            "h3_code": "def solve_h3():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT);')\n    conn.execute('INSERT INTO t VALUES (1);')\n    conn.execute('DELETE FROM t WHERE id = 1;')\n    conn.commit()\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "h3_test": "assert solve_h3() == 0",
            "h4_code": "def solve_h4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val TEXT);')\n    conn.execute(\"INSERT INTO t VALUES (1, 'old');\")\n    conn.execute(\"UPDATE t SET val = 'new' WHERE id = 1;\")\n    conn.commit()\n    return conn.execute('SELECT val FROM t WHERE id = 1;').fetchone()[0]", "h4_test": "assert solve_h4() == 'new'",
            "h5_code": "def solve_h5(sql_script):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.executescript(sql_script)\n    return conn.execute('SELECT COUNT(*) FROM t1;').fetchone()[0]", "h5_test": "assert solve_h5('CREATE TABLE t1 (x INT); INSERT INTO t1 VALUES (1);') == 1",
            "rob_code": "def process_telemetry(data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (val REAL);')\n    conn.executemany('INSERT INTO t VALUES (?);', [(x,) for x in data])\n    cnt = conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]\n    return {'sqlite_inserted': cnt}", "rob_test": "assert process_telemetry([1.0, 2.0])['sqlite_inserted'] == 2"
        }
    ),
    make_topic_data(
        topic_id="8.3", title="Connecting to Databases and Creating Tables", module=8, module_title="Databases",
        directory="03_connecting_creating_tables", summary="Connection management, cursors, table schemas, and data types.",
        why_it_matters="Establishing clean database schemas prevents data corruption and type mismatch.",
        objectives=["Establish database connections.", "Use cursors for statement execution.", "Define primary and foreign keys."],
        prerequisites=["Topic 8.2 SQLite"], domain="fleet operations centre", concepts=["Connection", "Cursor", "Schema", "Foreign Keys"],
        code_snippets={
            "syntax": "conn = sqlite3.connect('db.sqlite')\ncur = conn.cursor()", "basic": "import sqlite3\nconn = sqlite3.connect(':memory:')\ncur = conn.cursor()\ncur.execute('CREATE TABLE robots (id INT PRIMARY KEY, name TEXT);')",
            "intermediate": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('PRAGMA foreign_keys = ON;')\nconn.execute('''\nCREATE TABLE robots (id INT PRIMARY KEY);\nCREATE TABLE sensors (id INT, robot_id INT, FOREIGN KEY(robot_id) REFERENCES robots(id));\n''')",
            "advanced": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE INDEX idx_robots_name ON robots(name);')",
            "walkthrough": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('''\nCREATE TABLE fleet (\n    robot_id TEXT PRIMARY KEY,\n    battery_pct REAL NOT NULL,\n    status TEXT DEFAULT 'IDLE'\n);\n''')\nprint('Fleet table created')",
            "pythonic": "with sqlite3.connect(':memory:') as conn:\n    conn.execute('CREATE TABLE t (id INT)')", "engineering": "import sqlite3\ndef create_database_schema(db_conn):\n    db_conn.executescript('''\n        CREATE TABLE IF NOT EXISTS fleet (\n            id TEXT PRIMARY KEY,\n            model TEXT NOT NULL\n        );\n        CREATE TABLE IF NOT EXISTS telemetry (\n            id INTEGER PRIMARY KEY AUTOINCREMENT,\n            robot_id TEXT NOT NULL,\n            voltage REAL NOT NULL,\n            FOREIGN KEY(robot_id) REFERENCES fleet(id)\n        );\n    ''')\n    db_conn.commit()",
            "m1_code": "def solve_m1():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    cur = conn.cursor()\n    return cur is not None", "m1_test": "assert solve_m1() is True",
            "m2_code": "def solve_m2():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT PRIMARY KEY, name TEXT NOT NULL);')\n    return True", "m2_test": "assert solve_m2() is True",
            "m3_code": "def solve_m3():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('PRAGMA foreign_keys = ON;')\n    conn.execute('CREATE TABLE p (id INT PRIMARY KEY);')\n    conn.execute('CREATE TABLE c (id INT, p_id INT, FOREIGN KEY(p_id) REFERENCES p(id));')\n    return True", "m3_test": "assert solve_m3() is True",
            "m4_code": "def solve_m4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val TEXT DEFAULT \"N/A\");')\n    conn.execute('INSERT INTO t (id) VALUES (1);')\n    return conn.execute('SELECT val FROM t;').fetchone()[0]", "m4_test": "assert solve_m4() == 'N/A'",
            "m5_code": "def solve_m5():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, name TEXT);')\n    conn.execute('CREATE INDEX idx_t_name ON t(name);')\n    return True", "m5_test": "assert solve_m5() is True",
            "h1_code": "def solve_h1(table_name, columns_dict):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    col_defs = ', '.join(f'{k} {v}' for k, v in columns_dict.items())\n    conn.execute(f'CREATE TABLE {table_name} ({col_defs});')\n    return True", "h1_test": "assert solve_h1('t', {'id': 'INT PRIMARY KEY', 'val': 'TEXT'}) is True",
            "h2_code": "def solve_h2():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT);')\n    cur = conn.execute(\"SELECT name FROM sqlite_master WHERE type='table' AND name='t';\")\n    return cur.fetchone()[0]", "h2_test": "assert solve_h2() == 't'",
            "h3_code": "def solve_h3():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val TEXT);')\n    cur = conn.execute('PRAGMA table_info(t);')\n    return [row[1] for row in cur.fetchall()]", "h3_test": "assert solve_h3() == ['id', 'val']",
            "h4_code": "def solve_h4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT UNIQUE);')\n    conn.execute('INSERT INTO t VALUES (1);')\n    try:\n        conn.execute('INSERT INTO t VALUES (1);')\n        return False\n    except sqlite3.IntegrityError:\n        return True", "h4_test": "assert solve_h4() is True",
            "h5_code": "def solve_h5():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val REAL CHECK(val >= 0));')\n    try:\n        conn.execute('INSERT INTO t VALUES (1, -5);')\n        return False\n    except sqlite3.IntegrityError:\n        return True", "h5_test": "assert solve_h5() is True",
            "rob_code": "def process_telemetry(data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE telemetry (id INTEGER PRIMARY KEY, reading REAL);')\n    conn.executemany('INSERT INTO telemetry (reading) VALUES (?);', [(x,) for x in data])\n    return {'table_created': True, 'count': len(data)}", "rob_test": "assert process_telemetry([1.0])['table_created'] is True"
        }
    ),
    make_topic_data(
        topic_id="8.4", title="CRUD Operations", module=8, module_title="Databases",
        directory="04_crud_operations", summary="Create, Read, Update, Delete queries and data manipulation.",
        why_it_matters="CRUD operations are the primary database interaction primitives.",
        objectives=["Execute INSERT, SELECT, UPDATE, and DELETE statements.", "Fetch query results with fetchone() and fetchall().", "Handle bulk operations."],
        prerequisites=["Topic 8.3 Connecting to DBs"], domain="fleet operations centre", concepts=["CRUD", "INSERT", "SELECT", "UPDATE", "DELETE"],
        code_snippets={
            "syntax": "conn.execute('INSERT INTO t VALUES (1)')\nconn.execute('SELECT * FROM t')", "basic": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (id INT, name TEXT)')\nconn.execute(\"INSERT INTO t VALUES (1, 'R1')\")\nres = conn.execute('SELECT * FROM t').fetchall()",
            "intermediate": "conn.execute(\"UPDATE t SET name = 'R2' WHERE id = 1\")\nconn.execute('DELETE FROM t WHERE id = 1')", "advanced": "cur = conn.cursor()\ncur.execute('SELECT * FROM t')\nwhile row := cur.fetchone():\n    print(row)",
            "walkthrough": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE fleet (id INT, status TEXT)')\nconn.execute(\"INSERT INTO fleet VALUES (101, 'IDLE')\")\nconn.execute(\"UPDATE fleet SET status = 'ACTIVE' WHERE id = 101\")\nrow = conn.execute('SELECT * FROM fleet WHERE id = 101').fetchone()\nprint('Updated row:', row)",
            "pythonic": "rows = conn.execute('SELECT * FROM t').fetchall()", "engineering": "class FleetDB:\n    def __init__(self, conn):\n        self.conn = conn\n    def add_robot(self, robot_id, name):\n        self.conn.execute('INSERT INTO fleet VALUES (?, ?)', (robot_id, name))\n        self.conn.commit()\n    def get_robot(self, robot_id):\n        return self.conn.execute('SELECT * FROM fleet WHERE id = ?', (robot_id,)).fetchone()",
            "m1_code": "def solve_m1(table, val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute(f'CREATE TABLE {table} (x INT);')\n    conn.execute(f'INSERT INTO {table} VALUES (?);', (val,))\n    return conn.execute(f'SELECT x FROM {table};').fetchone()[0]", "m1_test": "assert solve_m1('t', 10) == 10",
            "m2_code": "def solve_m2(vals):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.executemany('INSERT INTO t VALUES (?);', [(v,) for v in vals])\n    return [row[0] for row in conn.execute('SELECT x FROM t;').fetchall()]", "m2_test": "assert solve_m2([1, 2]) == [1, 2]",
            "m3_code": "def solve_m3(old_val, new_val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.execute('INSERT INTO t VALUES (?);', (old_val,))\n    conn.execute('UPDATE t SET x = ? WHERE x = ?;', (new_val, old_val))\n    return conn.execute('SELECT x FROM t;').fetchone()[0]", "m3_test": "assert solve_m3(1, 2) == 2",
            "m4_code": "def solve_m4(del_val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.execute('INSERT INTO t VALUES (10);')\n    conn.execute('DELETE FROM t WHERE x = ?;', (del_val,))\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m4_test": "assert solve_m4(10) == 0",
            "m5_code": "def solve_m5():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.executemany('INSERT INTO t VALUES (?);', [(1,), (2,), (3,)])\n    cur = conn.execute('SELECT x FROM t;')\n    return cur.fetchone()[0], cur.fetchmany(2)", "m5_test": "assert solve_m5()[0] == 1",
            "h1_code": "def solve_h1(records):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT PRIMARY KEY, name TEXT);')\n    for r in records:\n        conn.execute('INSERT INTO t VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET name=excluded.name;', r)\n    return conn.execute('SELECT name FROM t WHERE id = 1;').fetchone()[0]", "h1_test": "assert solve_h1([(1, 'a'), (1, 'b')]) == 'b'",
            "h2_code": "def solve_h2(d_records):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val TEXT);')\n    for d in d_records:\n        conn.execute('INSERT INTO t VALUES (:id, :val);', d)\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "h2_test": "assert solve_h2([{'id': 1, 'val': 'a'}]) == 1",
            "h3_code": "def solve_h3():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT);')\n    conn.executemany('INSERT INTO t VALUES (?);', [(i,) for i in range(10)])\n    conn.execute('DELETE FROM t WHERE id % 2 == 0;')\n    return [r[0] for r in conn.execute('SELECT id FROM t;').fetchall()]", "h3_test": "assert solve_h3() == [1, 3, 5, 7, 9]",
            "h4_code": "def solve_h4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, status TEXT);')\n    conn.executemany('INSERT INTO t VALUES (?, ?);', [(1, 'OFF'), (2, 'OFF')])\n    conn.execute(\"UPDATE t SET status = 'ON';\")\n    return [r[0] for r in conn.execute('SELECT DISTINCT status FROM t;').fetchall()]", "h4_test": "assert solve_h4() == ['ON']",
            "h5_code": "def solve_h5(min_val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val REAL);')\n    conn.executemany('INSERT INTO t VALUES (?, ?);', [(1, 10.0), (2, 20.0)])\n    return conn.execute('SELECT * FROM t WHERE val >= ?;', (min_val,)).fetchall()", "h5_test": "assert len(solve_h5(15.0)) == 1",
            "rob_code": "def process_telemetry(data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE telemetry (val REAL);')\n    conn.executemany('INSERT INTO telemetry VALUES (?);', [(x,) for x in data])\n    rows = conn.execute('SELECT * FROM telemetry;').fetchall()\n    return {'crud_read': len(rows)}", "rob_test": "assert process_telemetry([1.0, 2.0])['crud_read'] == 2"
        }
    ),
    make_topic_data(
        topic_id="8.5", title="Parameterized Queries and SQL Injection", module=8, module_title="Databases",
        directory="05_parameterized_queries", summary="SQL injection vulnerabilities, string formatting risks, and parameterized placeholders (?).",
        why_it_matters="Parameterized queries protect applications from critical SQL injection security vulnerabilities.",
        objectives=["Identify SQL injection risks.", "Use parameterized placeholders (?).", "Never concatenate untrusted user input into SQL."],
        prerequisites=["Topic 8.4 CRUD Operations"], domain="fleet operations centre", concepts=["SQL Injection", "Parameterized Queries", "Placeholders"],
        code_snippets={
            "syntax": "# SAFE:\n# conn.execute('SELECT * FROM users WHERE name = ?', (username,))\n# UNSAFE: f'SELECT * FROM users WHERE name = \"{username}\"'",
            "basic": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (name TEXT)')\nuser_input = \"admin' OR '1'='1\"\n# Parameterized query handles quotes safely\nconn.execute('SELECT * FROM t WHERE name = ?', (user_input,))",
            "intermediate": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (id INT, val TEXT)')\nparams = {'id': 1, 'val': 'test'}\nconn.execute('INSERT INTO t VALUES (:id, :val)', params)",
            "advanced": "def safe_query(conn, table_name, param_val):\n    # Note: table names cannot be parameterized, validate table_name against whitelist!\n    if not table_name.isidentifier(): raise ValueError('Invalid table')\n    return conn.execute(f'SELECT * FROM {table_name} WHERE col = ?', (param_val,)).fetchall()",
            "walkthrough": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE users (user TEXT, role TEXT)')\nconn.execute(\"INSERT INTO users VALUES ('admin', 'ADMIN')\")\nmalicious = \"' OR '1'='1\"\n# Parameterized query prevents injection\nres = conn.execute('SELECT * FROM users WHERE user = ?', (malicious,)).fetchall()\nprint('Injected query result count:', len(res))",
            "pythonic": "conn.execute('SELECT * FROM t WHERE id = ?', (item_id,))", "engineering": "class SafeFleetRepository:\n    def __init__(self, conn):\n        self.conn = conn\n    def find_robot_by_name(self, name_str):\n        query = 'SELECT * FROM fleet WHERE name = ?;'\n        return self.conn.execute(query, (name_str,)).fetchall()",
            "m1_code": "def solve_m1(val):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x TEXT);')\n    conn.execute('INSERT INTO t VALUES (?);', (val,))\n    return conn.execute('SELECT x FROM t WHERE x = ?;', (val,)).fetchone()[0]", "m1_test": "assert solve_m1(\"' OR 1=1 --\") == \"' OR 1=1 --\"",
            "m2_code": "def solve_m2(d):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, name TEXT);')\n    conn.execute('INSERT INTO t VALUES (:id, :name);', d)\n    return conn.execute('SELECT name FROM t WHERE id = :id;', d).fetchone()[0]", "m2_test": "assert solve_m2({'id': 1, 'name': 'A'}) == 'A'",
            "m3_code": "def solve_m3(vals):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    placeholders = ', '.join('?' for _ in vals)\n    query = f'SELECT * FROM t WHERE x IN ({placeholders});'\n    return query", "m3_test": "assert 'IN (?, ?)' in solve_m3([1, 2])",
            "m4_code": "def solve_m4(query_str):\n    return '?' in query_str or ':' in query_str", "m4_test": "assert solve_m4('SELECT * FROM t WHERE x = ?') is True",
            "m5_code": "def solve_m5(untrusted_name):\n    if not untrusted_name.isidentifier():\n        raise ValueError('Unsafe name')\n    return f'SELECT * FROM {untrusted_name};'", "m5_test": "assert solve_m5('fleet') == 'SELECT * FROM fleet;'",
            "h1_code": "def solve_h1(search_term):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (name TEXT);')\n    conn.execute(\"INSERT INTO t VALUES ('robot_a'), ('drone_b');\")\n    pattern = f'%{search_term}%'\n    return [r[0] for r in conn.execute('SELECT name FROM t WHERE name LIKE ?;', (pattern,)).fetchall()]", "h1_test": "assert solve_h1('robot') == ['robot_a']",
            "h2_code": "def solve_h2(filters_dict):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (a INT, b TEXT);')\n    conditions = []\n    params = []\n    for k, v in filters_dict.items():\n        conditions.append(f'{k} = ?')\n        params.append(v)\n    where_clause = ' AND '.join(conditions) if conditions else '1=1'\n    query = f'SELECT * FROM t WHERE {where_clause};'\n    return query, params", "h2_test": "assert 'a = ?' in solve_h2({'a': 1})[0]",
            "h3_code": "def solve_h3(input_str):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (val TEXT);')\n    conn.execute('INSERT INTO t VALUES (?);', (input_str,))\n    return conn.execute('SELECT val FROM t WHERE val = ?;', (input_str,)).fetchone()[0]", "h3_test": "assert solve_h3('1; DROP TABLE t;') == '1; DROP TABLE t;'",
            "h4_code": "def solve_h4(sql_template, params):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, val TEXT);')\n    conn.execute(sql_template, params)\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "h4_test": "assert solve_h4('INSERT INTO t VALUES (?, ?);', (1, 'a')) == 1",
            "h5_code": "def solve_h5(params_list):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT, y TEXT);')\n    conn.executemany('INSERT INTO t VALUES (?, ?);', params_list)\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "h5_test": "assert solve_h5([(1, 'a'), (2, 'b')]) == 2",
            "rob_code": "def process_telemetry(data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE telemetry (val REAL);')\n    val = data[0] if data else 0.0\n    conn.execute('INSERT INTO telemetry VALUES (?);', (val,))\n    res = conn.execute('SELECT val FROM telemetry WHERE val = ?;', (val,)).fetchone()[0]\n    return {'parameterized_val': res}", "rob_test": "assert process_telemetry([42.0])['parameterized_val'] == 42.0"
        }
    ),
    make_topic_data(
        topic_id="8.6", title="Transactions", module=8, module_title="Databases",
        directory="06_transactions", summary="ACID properties, commit, rollback, and transaction context managers.",
        why_it_matters="Transactions guarantee atomic state transitions, preventing partial updates during failures.",
        objectives=["Understand ACID properties.", "Commit and rollback database transactions.", "Use connection as context manager for auto-commit/rollback."],
        prerequisites=["Topic 8.5 Parameterized Queries"], domain="fleet operations centre", concepts=["Transactions", "ACID", "Commit", "Rollback"],
        code_snippets={
            "syntax": "conn.commit()\nconn.rollback()", "basic": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (x INT)')\ntry:\n    conn.execute('INSERT INTO t VALUES (1)')\n    conn.commit()\nexcept Exception:\n    conn.rollback()",
            "intermediate": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (x INT PRIMARY KEY)')\nwith conn:\n    conn.execute('INSERT INTO t VALUES (1)')\n    # Auto-commits on block exit if no exception", "advanced": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE t (x INT PRIMARY KEY)')\ntry:\n    with conn:\n        conn.execute('INSERT INTO t VALUES (1)')\n        conn.execute('INSERT INTO t VALUES (1)') # Duplicate primary key error!\nexcept sqlite3.IntegrityError:\n    print('Transaction rolled back automatically')",
            "walkthrough": "import sqlite3\nconn = sqlite3.connect(':memory:')\nconn.execute('CREATE TABLE accounts (id INT, bal REAL)')\nconn.execute('INSERT INTO accounts VALUES (1, 100.0), (2, 50.0)')\nconn.commit()\ntry:\n    conn.execute('UPDATE accounts SET bal = bal - 30 WHERE id = 1')\n    conn.execute('UPDATE accounts SET bal = bal + 30 WHERE id = 2')\n    conn.commit()\nexcept Exception:\n    conn.rollback()\nprint('Balances:', conn.execute('SELECT bal FROM accounts').fetchall())",
            "pythonic": "with conn:\n    conn.execute('INSERT INTO t VALUES (?)', (1,))", "engineering": "def transfer_funds(conn, src_id, dst_id, amount):\n    try:\n        with conn:\n            conn.execute('UPDATE accounts SET bal = bal - ? WHERE id = ?', (amount, src_id))\n            conn.execute('UPDATE accounts SET bal = bal + ? WHERE id = ?', (amount, dst_id))\n        return True\n    except sqlite3.Error:\n        return False",
            "m1_code": "def solve_m1():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.execute('INSERT INTO t VALUES (1);')\n    conn.commit()\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m1_test": "assert solve_m1() == 1",
            "m2_code": "def solve_m2():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.execute('INSERT INTO t VALUES (1);')\n    conn.rollback()\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m2_test": "assert solve_m2() == 0",
            "m3_code": "def solve_m3():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    with conn:\n        conn.execute('INSERT INTO t VALUES (10);')\n    return conn.execute('SELECT x FROM t;').fetchone()[0]", "m3_test": "assert solve_m3() == 10",
            "m4_code": "def solve_m4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT PRIMARY KEY);')\n    try:\n        with conn:\n            conn.execute('INSERT INTO t VALUES (1);')\n            conn.execute('INSERT INTO t VALUES (1);')\n    except sqlite3.IntegrityError:\n        pass\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m4_test": "assert solve_m4() == 0",
            "m5_code": "def solve_m5(fail_second):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT PRIMARY KEY);')\n    try:\n        with conn:\n            conn.execute('INSERT INTO t VALUES (1);')\n            if fail_second:\n                conn.execute('INSERT INTO t VALUES (1);')\n            else:\n                conn.execute('INSERT INTO t VALUES (2);')\n    except sqlite3.IntegrityError:\n        pass\n    return conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "m5_test": "assert solve_m5(True) == 0 and solve_m5(False) == 2",
            "h1_code": "def solve_h1(operations):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (val INT);')\n    try:\n        with conn:\n            for op in operations:\n                conn.execute('INSERT INTO t VALUES (?);', (op,))\n                if op < 0:\n                    raise ValueError('Negative operation')\n        return True, conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]\n    except Exception:\n        return False, conn.execute('SELECT COUNT(*) FROM t;').fetchone()[0]", "h1_test": "assert solve_h1([1, -1])[0] is False and solve_h1([1, -1])[1] == 0",
            "h2_code": "def solve_h2():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT, bal REAL);')\n    conn.execute('INSERT INTO t VALUES (1, 100), (2, 50);')\n    conn.commit()\n    try:\n        with conn:\n            conn.execute('UPDATE t SET bal = bal - 20 WHERE id = 1;')\n            conn.execute('UPDATE t SET bal = bal + 20 WHERE id = 2;')\n    except Exception:\n        pass\n    return [r[0] for r in conn.execute('SELECT bal FROM t ORDER BY id;').fetchall()]", "h2_test": "assert solve_h2() == [80.0, 70.0]",
            "h3_code": "def solve_h3(statements):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (x INT);')\n    try:\n        with conn:\n            for stmt in statements:\n                conn.execute(stmt)\n        return True\n    except Exception:\n        return False", "h3_test": "assert solve_h3(['INSERT INTO t VALUES (1);']) is True",
            "h4_code": "def solve_h4():\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.isolation_level = 'EXCLUSIVE'\n    conn.execute('CREATE TABLE t (x INT);')\n    conn.commit()\n    return conn.isolation_level", "h4_test": "assert solve_h4() == 'EXCLUSIVE'",
            "h5_code": "def solve_h5(batch_data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE t (id INT PRIMARY KEY, val TEXT);')\n    inserted = 0\n    for item in batch_data:\n        try:\n            with conn:\n                conn.execute('INSERT INTO t VALUES (?, ?);', item)\n            inserted += 1\n        except sqlite3.IntegrityError:\n            continue\n    return inserted", "h5_test": "assert solve_h5([(1, 'a'), (1, 'b'), (2, 'c')]) == 2",
            "rob_code": "def process_telemetry(data):\n    import sqlite3\n    conn = sqlite3.connect(':memory:')\n    conn.execute('CREATE TABLE telemetry (val REAL);')\n    with conn:\n        conn.executemany('INSERT INTO telemetry VALUES (?);', [(x,) for x in data])\n    cnt = conn.execute('SELECT COUNT(*) FROM telemetry;').fetchone()[0]\n    return {'transaction_inserted': cnt}", "rob_test": "assert process_telemetry([1.0, 2.0])['transaction_inserted'] == 2"
        }
    ),
    make_topic_data(
        topic_id="8.7", title="ORMs", module=8, module_title="Databases",
        directory="07_orms", summary="SQLAlchemy core and ORM declarative mapping, Base, Session, and mapped models.",
        why_it_matters="ORMs map database tables directly to Python classes, providing high-level data abstractions.",
        objectives=["Define SQLAlchemy models with declarative base.", "Manage sessions and query objects.", "Understand ORM vs raw SQL trade-offs."],
        prerequisites=["Topic 8.6 Transactions"], domain="fleet operations centre", concepts=["ORM", "SQLAlchemy", "Declarative Base", "Session"],
        code_snippets={
            "syntax": "from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, sessionmaker\nBase = declarative_base()",
            "basic": "from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base\nBase = declarative_base()\nclass Robot(Base):\n    __tablename__ = 'robots'\n    id = Column(Integer, primary_key=True)\n    name = Column(String)\nengine = create_engine('sqlite:///:memory:')\nBase.metadata.create_all(engine)",
            "intermediate": "from sqlalchemy.orm import sessionmaker\nSession = sessionmaker(bind=engine)\nsession = Session()\nr1 = Robot(id=1, name='ROBO-1')\nsession.add(r1)\nsession.commit()",
            "advanced": "robots = session.query(Robot).filter(Robot.name == 'ROBO-1').all()",
            "walkthrough": "from sqlalchemy import create_engine, Column, Integer, String\nfrom sqlalchemy.orm import declarative_base, sessionmaker\nBase = declarative_base()\nclass FleetRobot(Base):\n    __tablename__ = 'fleet'\n    id = Column(Integer, primary_key=True)\n    model = Column(String)\nengine = create_engine('sqlite:///:memory:')\nBase.metadata.create_all(engine)\nSession = sessionmaker(bind=engine)\ns = Session()\ns.add(FleetRobot(id=1, model='X1'))\ns.commit()\nr = s.query(FleetRobot).first()\nprint('ORM Robot:', r.model)",
            "pythonic": "robot = session.get(FleetRobot, 1)", "engineering": "from sqlalchemy import create_engine, Column, Integer, String, Float\nfrom sqlalchemy.orm import declarative_base, sessionmaker\nBase = declarative_base()\nclass TelemetryRecord(Base):\n    __tablename__ = 'telemetry'\n    id = Column(Integer, primary_key=True)\n    robot_id = Column(String, nullable=False)\n    battery = Column(Float, nullable=False)\ndef init_orm_db():\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    return sessionmaker(bind=engine)()",
            "m1_code": "def solve_m1():\n    from sqlalchemy import create_engine, Column, Integer, String\n    from sqlalchemy.orm import declarative_base\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    return 't' in Base.metadata.tables", "m1_test": "assert solve_m1() is True",
            "m2_code": "def solve_m2(val):\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True, autoincrement=True)\n        val = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add(T(val=val))\n    s.commit()\n    return s.query(T).first().val", "m2_test": "assert solve_m2(42) == 42",
            "m3_code": "def solve_m3(vals):\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True, autoincrement=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(v=x) for x in vals])\n    s.commit()\n    return s.query(T).count()", "m3_test": "assert solve_m3([1, 2, 3]) == 3",
            "m4_code": "def solve_m4(target_v):\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(id=1, v=10), T(id=2, v=20)])\n    s.commit()\n    res = s.query(T).filter(T.v == target_v).first()\n    return res.id if res else None", "m4_test": "assert solve_m4(20) == 2",
            "m5_code": "def solve_m5(id_val, new_v):\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add(T(id=id_val, v=0))\n    s.commit()\n    item = s.query(T).get(id_val)\n    item.v = new_v\n    s.commit()\n    return s.query(T).get(id_val).v", "m5_test": "assert solve_m5(1, 100) == 100",
            "h1_code": "def solve_h1():\n    from sqlalchemy import create_engine, Column, Integer, String, ForeignKey\n    from sqlalchemy.orm import declarative_base, relationship, sessionmaker\n    Base = declarative_base()\n    class Parent(Base):\n        __tablename__ = 'p'\n        id = Column(Integer, primary_key=True)\n        children = relationship('Child', back_populates='parent')\n    class Child(Base):\n        __tablename__ = 'c'\n        id = Column(Integer, primary_key=True)\n        p_id = Column(Integer, ForeignKey('p.id'))\n        parent = relationship('Parent', back_populates='children')\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    p = Parent(id=1); c = Child(id=10, parent=p)\n    s.add(p); s.commit()\n    return len(s.query(Parent).get(1).children)", "h1_test": "assert solve_h1() == 1",
            "h2_code": "def solve_h2():\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(id=1, v=10), T(id=2, v=20)])\n    s.commit()\n    s.query(T).filter(T.id == 1).delete()\n    s.commit()\n    return s.query(T).count()", "h2_test": "assert solve_h2() == 1",
            "h3_code": "def solve_h3():\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(id=i, v=i*10) for i in range(1, 6)])\n    s.commit()\n    res = s.query(T).order_by(T.v.desc()).all()\n    return [item.v for item in res]", "h3_test": "assert solve_h3() == [50, 40, 30, 20, 10]",
            "h4_code": "def solve_h4():\n    from sqlalchemy import create_engine, Column, Integer, func\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(id=1, v=10), T(id=2, v=20)])\n    s.commit()\n    return s.query(func.avg(T.v)).scalar()", "h4_test": "assert solve_h4() == 15.0",
            "h5_code": "def solve_h5(min_v):\n    from sqlalchemy import create_engine, Column, Integer\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class T(Base):\n        __tablename__ = 't'\n        id = Column(Integer, primary_key=True)\n        v = Column(Integer)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([T(id=1, v=10), T(id=2, v=20)])\n    s.commit()\n    return [item.id for item in s.query(T).filter(T.v >= min_v).all()]", "h5_test": "assert solve_h5(15) == [2]",
            "rob_code": "def process_telemetry(data):\n    from sqlalchemy import create_engine, Column, Integer, Float\n    from sqlalchemy.orm import declarative_base, sessionmaker\n    Base = declarative_base()\n    class Telemetry(Base):\n        __tablename__ = 'telemetry'\n        id = Column(Integer, primary_key=True, autoincrement=True)\n        val = Column(Float)\n    engine = create_engine('sqlite:///:memory:')\n    Base.metadata.create_all(engine)\n    s = sessionmaker(bind=engine)()\n    s.add_all([Telemetry(val=x) for x in data])\n    s.commit()\n    cnt = s.query(Telemetry).count()\n    return {'orm_count': cnt}", "rob_test": "assert process_telemetry([1.0, 2.0])['orm_count'] == 2"
        }
    ),
    make_topic_data(
        topic_id="8.8", title="External Databases", module=8, module_title="Databases",
        directory="08_external_databases", summary="Connecting to external RDBMS (PostgreSQL, MySQL), psycopg2, mysql-connector, and production deployment patterns.",
        why_it_matters="Production fleet deployments connect to external scaled databases like PostgreSQL or MySQL.",
        objectives=["Understand PostgreSQL and MySQL connectors.", "Configure connection strings and connection pools.", "Deploy production database configurations."],
        prerequisites=["Topic 8.7 ORMs"], domain="fleet operations centre", concepts=["PostgreSQL", "MySQL", "psycopg2", "Connection Pooling"],
        code_snippets={
            "syntax": "# PostgreSQL connection string format:\n# postgresql://user:password@localhost:5432/fleet_db",
            "basic": "def format_pg_url(user, password, host, port, dbname):\n    return f'postgresql://{user}:{password}@{host}:{port}/{dbname}'",
            "intermediate": "def create_db_engine(url_str):\n    from sqlalchemy import create_engine\n    return create_engine(url_str, pool_size=5, max_overflow=10)",
            "advanced": "def demonstrate_production_pooling():\n    from sqlalchemy.pool import QueuePool\n    return 'QueuePool configured for 20 concurrent connections'",
            "walkthrough": "url = format_pg_url('admin', 'secret', 'db.internal', 5432, 'robots')\nprint('Production DB URL:', url)",
            "pythonic": "url = 'sqlite:///:memory:'  # Local development fallback", "engineering": "from sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker\ndef get_production_session_factory(db_url):\n    engine = create_engine(db_url, pool_size=10, max_overflow=20, pool_pre_ping=True)\n    return sessionmaker(bind=engine)",
            "m1_code": "def solve_m1(user, pwd, host, db):\n    return f'postgresql://{user}:{pwd}@{host}:5432/{db}'", "m1_test": "assert solve_m1('u', 'p', 'h', 'd') == 'postgresql://u:p@h:5432/d'",
            "m2_code": "def solve_m2(user, pwd, host, db):\n    return f'mysql+mysqlconnector://{user}:{pwd}@{host}:3306/{db}'", "m2_test": "assert 'mysql' in solve_m2('u', 'p', 'h', 'd')",
            "m3_code": "def solve_m3(driver_name):\n    return driver_name in ('psycopg2', 'mysql-connector-python', 'sqlite3')", "m3_test": "assert solve_m3('psycopg2') is True",
            "m4_code": "def solve_m4(pool_size, max_overflow):\n    return {'pool_size': pool_size, 'max_overflow': max_overflow}", "m4_test": "assert solve_m4(5, 10) == {'pool_size': 5, 'max_overflow': 10}",
            "m5_code": "def solve_m5(env_dict):\n    return env_dict.get('DATABASE_URL', 'sqlite:///:memory:')", "m5_test": "assert solve_m5({}) == 'sqlite:///:memory:'",
            "h1_code": "def solve_h1(db_type, user, pwd, host, port, db):\n    drivers = {'postgres': f'postgresql://{user}:{pwd}@{host}:{port}/{db}', 'mysql': f'mysql+mysqlconnector://{user}:{pwd}@{host}:{port}/{db}'}\n    return drivers.get(db_type, 'sqlite:///:memory:')", "h1_test": "assert solve_h1('postgres', 'u', 'p', 'h', 5432, 'd').startswith('postgresql')",
            "h2_code": "def solve_h2(conn_str):\n    from sqlalchemy import create_engine\n    try:\n        engine = create_engine('sqlite:///:memory:')\n        return engine.name\n    except Exception as e:\n        return str(e)", "h2_test": "assert solve_h2('sqlite:///:memory:') == 'sqlite'",
            "h3_code": "def solve_h3(is_prod, prod_url):\n    return prod_url if is_prod else 'sqlite:///:memory:'", "h3_test": "assert solve_h3(False, 'postgresql://user:pass@host/db') == 'sqlite:///:memory:'",
            "h4_code": "def solve_h4(params_dict):\n    return f\"host={params_dict.get('host')} dbname={params_dict.get('db')} user={params_dict.get('user')}\"", "h4_test": "assert 'host=localhost' in solve_h4({'host': 'localhost', 'db': 'test', 'user': 'admin'})",
            "h5_code": "def solve_h5(conn_string):\n    return conn_string.startswith('postgresql') or conn_string.startswith('mysql') or conn_string.startswith('sqlite')", "h5_test": "assert solve_h5('postgresql://a:b@c/d') is True",
            "rob_code": "def process_telemetry(data):\n    db_url = 'sqlite:///:memory:'\n    return {'active_db_url': db_url, 'count': len(data)}", "rob_test": "assert process_telemetry([1])['active_db_url'] == 'sqlite:///:memory:'"
        }
    )
]
