"""Module 6 — Object-Oriented Programming (topics 6.1 - 6.8)."""

from __future__ import annotations
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from self_created_tools.topic_builder import make_topic_data

TOPICS = [
    make_topic_data(
        topic_id="6.1", title="OOP Fundamentals", module=6, module_title="Object-Oriented Programming",
        directory="01_oop_fundamentals", summary="Classes, instances, __init__, self, and instance attributes.",
        why_it_matters="Object-oriented programming structures state and behavior into cohesive entities.",
        objectives=["Define classes with __init__.", "Instantiate objects and pass self.", "Manage instance attributes."],
        prerequisites=["Module 5 Error Handling"], domain="modular robotic arm", concepts=["Class", "Instance", "__init__", "self"],
        code_snippets={
            "syntax": "class Robot:\n    def __init__(self, name):\n        self.name = name", "basic": "r = Robot('ROBO-X')\nprint(r.name)",
            "intermediate": "class Joint:\n    def __init__(self, angle_deg=0.0):\n        self.angle = angle_deg\n    def move(self, delta):\n        self.angle += delta",
            "advanced": "class Arm:\n    def __init__(self, joints):\n        self.joints = joints",
            "walkthrough": "class Controller:\n    def __init__(self, id_str):\n        self.id = id_str\n        self.active = False\n    def start(self):\n        self.active = True",
            "pythonic": "class Point:\n    def __init__(self, x=0.0, y=0.0):\n        self.x, self.y = x, y", "engineering": "class MotorController:\n    def __init__(self, motor_id, max_rpm=3000):\n        self.motor_id = motor_id\n        self.max_rpm = max_rpm\n        self.current_rpm = 0.0\n    def set_speed(self, rpm):\n        self.current_rpm = min(rpm, self.max_rpm)",
            "m1_code": "class Robot:\n    def __init__(self, name):\n        self.name = name\ndef solve_m1(name):\n    return Robot(name).name", "m1_test": "assert solve_m1('R1') == 'R1'",
            "m2_code": "class Counter:\n    def __init__(self):\n        self.val = 0\n    def inc(self):\n        self.val += 1\ndef solve_m2():\n    c = Counter()\n    c.inc()\n    return c.val", "m2_test": "assert solve_m2() == 1",
            "m3_code": "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\ndef solve_m3(x, y):\n    p = Point(x, y)\n    return p.x, p.y", "m3_test": "assert solve_m3(1, 2) == (1, 2)",
            "m4_code": "class Accumulator:\n    def __init__(self):\n        self.total = 0\n    def add(self, x):\n        self.total += x\ndef solve_m4(vals):\n    a = Accumulator()\n    for v in vals: a.add(v)\n    return a.total", "m4_test": "assert solve_m4([1, 2, 3]) == 6",
            "m5_code": "class Toggle:\n    def __init__(self):\n        self.state = False\n    def flip(self):\n        self.state = not self.state\ndef solve_m5():\n    t = Toggle()\n    t.flip()\n    return t.state", "m5_test": "assert solve_m5() is True",
            "h1_code": "class BankAccount:\n    def __init__(self, balance=0):\n        self.balance = balance\n    def deposit(self, amt):\n        self.balance += amt\n    def withdraw(self, amt):\n        if amt <= self.balance:\n            self.balance -= amt\n            return True\n        return False\ndef solve_h1():\n    b = BankAccount(100)\n    b.deposit(50)\n    ok = b.withdraw(120)\n    return b.balance, ok", "h1_test": "assert solve_h1() == (30, True)",
            "h2_code": "class Stack:\n    def __init__(self):\n        self.items = []\n    def push(self, x):\n        self.items.append(x)\n    def pop(self):\n        return self.items.pop() if self.items else None\ndef solve_h2():\n    s = Stack(); s.push(1); s.push(2); return s.pop()", "h2_test": "assert solve_h2() == 2",
            "h3_code": "class Timer:\n    def __init__(self):\n        self.ticks = 0\n    def tick(self):\n        self.ticks += 1\n    def reset(self):\n        self.ticks = 0\ndef solve_h3():\n    t = Timer(); t.tick(); t.reset(); return t.ticks", "h3_test": "assert solve_h3() == 0",
            "h4_code": "class Item:\n    def __init__(self, name, price):\n        self.name = name\n        self.price = price\nclass ShoppingCart:\n    def __init__(self):\n        self.items = []\n    def add(self, item):\n        self.items.append(item)\n    def total(self):\n        return sum(i.price for i in self.items)\ndef solve_h4():\n    cart = ShoppingCart()\n    cart.add(Item('a', 10))\n    cart.add(Item('b', 20))\n    return cart.total()", "h4_test": "assert solve_h4() == 30",
            "h5_code": "class Node:\n    def __init__(self, val):\n        self.val = val\n        self.next = None\ndef solve_h5():\n    n1 = Node(1); n2 = Node(2); n1.next = n2\n    return n1.next.val", "h5_test": "assert solve_h5() == 2",
            "rob_code": "class RobotState:\n    def __init__(self, name):\n        self.name = name\n        self.active = True\ndef process_telemetry(data):\n    r = RobotState('ROBO-X')\n    return {'name': r.name, 'active': r.active, 'data_len': len(data)}", "rob_test": "assert process_telemetry([1])['active'] is True"
        }
    ),
    make_topic_data(
        topic_id="6.2", title="Encapsulation and Access Modifiers", module=6, module_title="Object-Oriented Programming",
        directory="02_encapsulation_access_modifiers", summary="Public, protected (_), private (__) attributes, and name mangling.",
        why_it_matters="Encapsulation hides internal state and exposes clean public interfaces.",
        objectives=["Use single underscore for protected members.", "Understand double underscore name mangling.", "Enforce API boundaries."],
        prerequisites=["Topic 6.1 OOP Fundamentals"], domain="modular robotic arm", concepts=["Encapsulation", "Protected", "Private", "Name Mangling"],
        code_snippets={
            "syntax": "class Safe:\n    def __init__(self):\n        self._protected = 1\n        self.__private = 2", "basic": "class Vault:\n    def __init__(self, secret):\n        self.__secret = secret\n    def get_secret(self):\n        return self.__secret",
            "intermediate": "class Device:\n    def __init__(self):\n        self._status = 'OFF'\n    def turn_on(self):\n        self._status = 'ON'", "advanced": "v = Vault('pass')\nprint(v._Vault__secret)  # Name mangled access",
            "walkthrough": "class ArmJoint:\n    def __init__(self, limit_deg):\n        self._angle = 0.0\n        self.__limit = limit_deg\n    def set_angle(self, angle):\n        if abs(angle) <= self.__limit:\n            self._angle = angle\n            return True\n        return False",
            "pythonic": "class EncapsulatedData:\n    def __init__(self, value):\n        self._value = value", "engineering": "class ProtectedBattery:\n    def __init__(self, capacity_wh):\n        self._capacity = capacity_wh\n        self.__charge_wh = capacity_wh\n    def get_soc_pct(self):\n        return (self.__charge_wh / self._capacity) * 100.0",
            "m1_code": "class Encap:\n    def __init__(self, val):\n        self._val = val\ndef solve_m1(v): return Encap(v)._val", "m1_test": "assert solve_m1(10) == 10",
            "m2_code": "class Priv:\n    def __init__(self, val):\n        self.__val = val\n    def get_val(self): return self.__val\ndef solve_m2(v): return Priv(v).get_val()", "m2_test": "assert solve_m2(20) == 20",
            "m3_code": "class Mangled:\n    def __init__(self, secret):\n        self.__secret = secret\ndef solve_m3(obj): return getattr(obj, '_Mangled__secret')", "m3_test": "m = Mangled('code'); assert solve_m3(m) == 'code'",
            "m4_code": "class Bounded:\n    def __init__(self, max_v):\n        self.__max = max_v\n        self._val = 0\n    def set_val(self, v):\n        if v <= self.__max: self._val = v\ndef solve_m4(v): b = Bounded(10); b.set_val(v); return b._val", "m4_test": "assert solve_m4(5) == 5 and solve_m4(15) == 0",
            "m5_code": "class Guard:\n    def __init__(self):\n        self._active = False\n    def is_active(self): return self._active\ndef solve_m5(): return Guard().is_active()", "m5_test": "assert solve_m5() is False",
            "h1_code": "class Account:\n    def __init__(self, balance):\n        self.__balance = balance\n    def get_balance(self): return self.__balance\n    def deposit(self, amt):\n        if amt > 0: self.__balance += amt\ndef solve_h1(): a = Account(100); a.deposit(50); return a.get_balance()", "h1_test": "assert solve_h1() == 150",
            "h2_code": "class SafeConfig:\n    def __init__(self, d):\n        self.__d = d.copy()\n    def get(self, k): return self.__d.get(k)\ndef solve_h2(): sc = SafeConfig({'a': 1}); return sc.get('a')", "h2_test": "assert solve_h2() == 1",
            "h3_code": "class ReadOnly:\n    def __init__(self, val):\n        self.__val = val\n    @property\n    def value(self): return self.__val\ndef solve_h3(): return ReadOnly(42).value", "h3_test": "assert solve_h3() == 42",
            "h4_code": "class KeyLock:\n    def __init__(self, key):\n        self.__key = key\n    def unlock(self, key):\n        return key == self.__key\ndef solve_h4(k): return KeyLock('secret').unlock(k)", "h4_test": "assert solve_h4('secret') is True and solve_h4('wrong') is False",
            "h5_code": "class LoggedData:\n    def __init__(self):\n        self._data = []\n    def add(self, x): self._data.append(x)\n    def count(self): return len(self._data)\ndef solve_h5(): ld = LoggedData(); ld.add(1); return ld.count()", "h5_test": "assert solve_h5() == 1",
            "rob_code": "class ProtectedJoint:\n    def __init__(self, name):\n        self._name = name\n        self.__active = True\n    def status(self): return {'name': self._name, 'active': self.__active}\ndef process_telemetry(data):\n    j = ProtectedJoint('J1')\n    return j.status()", "rob_test": "assert process_telemetry([])['active'] is True"
        }
    ),
    make_topic_data(
        topic_id="6.3", title="Inheritance", module=6, module_title="Object-Oriented Programming",
        directory="03_inheritance", summary="Single and multiple inheritance, super(), and Method Resolution Order (MRO).",
        why_it_matters="Inheritance allows subclasses to reuse and extend parent class behavior.",
        objectives=["Subclass existing classes.", "Use super() to call parent methods.", "Understand C3 linearization and MRO."],
        prerequisites=["Topic 6.2 Encapsulation"], domain="modular robotic arm", concepts=["Inheritance", "super()", "MRO"],
        code_snippets={
            "syntax": "class Parent:\n    pass\nclass Child(Parent):\n    pass", "basic": "class BaseRobot:\n    def ping(self):\n        return 'PONG'\nclass MobileRobot(BaseRobot):\n    pass",
            "intermediate": "class Animal:\n    def __init__(self, name):\n        self.name = name\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed", "advanced": "class A: pass\nclass B(A): pass\nprint(B.mro())",
            "walkthrough": "class Component:\n    def __init__(self, comp_id):\n        self.id = comp_id\nclass SensorComponent(Component):\n    def __init__(self, comp_id, sensor_type):\n        super().__init__(comp_id)\n        self.type = sensor_type",
            "pythonic": "class CustomList(list):\n    def first(self):\n        return self[0] if self else None", "engineering": "class BaseActuator:\n    def __init__(self, actuator_id):\n        self.id = actuator_id\n        self.enabled = False\n    def enable(self):\n        self.enabled = True\nclass ServoActuator(BaseActuator):\n    def __init__(self, actuator_id, angle_limit):\n        super().__init__(actuator_id)\n        self.limit = angle_limit",
            "m1_code": "class Parent:\n    def msg(self): return 'PARENT'\nclass Child(Parent): pass\ndef solve_m1(): return Child().msg()", "m1_test": "assert solve_m1() == 'PARENT'",
            "m2_code": "class Base:\n    def __init__(self, name):\n        self.name = name\nclass Sub(Base):\n    def __init__(self, name, val):\n        super().__init__(name)\n        self.val = val\ndef solve_m2(): s = Sub('a', 1); return s.name, s.val", "m2_test": "assert solve_m2() == ('a', 1)",
            "m3_code": "class A: pass\nclass B(A): pass\ndef solve_m3(): return issubclass(B, A)", "m3_test": "assert solve_m3() is True",
            "m4_code": "class Base:\n    def val(self): return 1\nclass Sub(Base):\n    def val(self): return super().val() + 10\ndef solve_m4(): return Sub().val()", "m4_test": "assert solve_m4() == 11",
            "m5_code": "class A: pass\nclass B: pass\nclass C(A, B): pass\ndef solve_m5(): return [cls.__name__ for cls in C.mro()]", "m5_test": "assert 'A' in solve_m5() and 'B' in solve_m5()",
            "h1_code": "class Shape:\n    def area(self): return 0.0\nclass Rectangle(Shape):\n    def __init__(self, w, h):\n        self.w, self.h = w, h\n    def area(self): return self.w * self.h\ndef solve_h1(): return Rectangle(3, 4).area()", "h1_test": "assert solve_h1() == 12",
            "h2_code": "class A:\n    def ping(self): return 'A'\nclass B(A):\n    def ping(self): return 'B-' + super().ping()\ndef solve_h2(): return B().ping()", "h2_test": "assert solve_h2() == 'B-A'",
            "h3_code": "class LoggedList(list):\n    def append(self, item):\n        super().append(item)\n        return 'APPENDED'\ndef solve_h3(): l = LoggedList(); res = l.append(10); return len(l), res", "h3_test": "assert solve_h3() == (1, 'APPENDED')",
            "h4_code": "class X: pass\nclass Y(X): pass\nclass Z(Y): pass\ndef solve_h4(): return isinstance(Z(), X)", "h4_test": "assert solve_h4() is True",
            "h5_code": "class Device:\n    def __init__(self, dev_id):\n        self.id = dev_id\nclass NetworkDevice(Device):\n    def __init__(self, dev_id, ip):\n        super().__init__(dev_id)\n        self.ip = ip\ndef solve_h5(): nd = NetworkDevice('D1', '127.0.0.1'); return nd.id, nd.ip", "h5_test": "assert solve_h5() == ('D1', '127.0.0.1')",
            "rob_code": "class BaseRobot:\n    def status(self): return 'OK'\nclass ArmRobot(BaseRobot):\n    def status(self): return 'ARM_' + super().status()\ndef process_telemetry(data):\n    r = ArmRobot()\n    return {'status': r.status()}", "rob_test": "assert process_telemetry([])['status'] == 'ARM_OK'"
        }
    ),
    make_topic_data(
        topic_id="6.4", title="Polymorphism and Abstraction", module=6, module_title="Object-Oriented Programming",
        directory="04_polymorphism_abstraction", summary="Method overriding, duck typing, abc module, and @abstractmethod.",
        why_it_matters="Polymorphism allows uniform treatment of different underlying class implementations.",
        objectives=["Override methods in subclasses.", "Use duck typing effectively.", "Define abstract base classes with abc."],
        prerequisites=["Topic 6.3 Inheritance"], domain="modular robotic arm", concepts=["Polymorphism", "Abstraction", "abc", "Duck Typing"],
        code_snippets={
            "syntax": "from abc import ABC, abstractmethod\nclass Base(ABC):\n    @abstractmethod\n    def run(self):\n        pass", "basic": "class Cat:\n    def speak(self): return 'Meow'\nclass Dog:\n    def speak(self): return 'Woof'\ndef make_speak(animal): return animal.speak()",
            "intermediate": "from abc import ABC, abstractmethod\nclass Sensor(ABC):\n    @abstractmethod\n    def read(self):\n        pass", "advanced": "class LidarSensor(Sensor):\n    def read(self):\n        return [1.0, 2.0]",
            "walkthrough": "from abc import ABC, abstractmethod\nclass AbstractActuator(ABC):\n    @abstractmethod\n    def set_target(self, target):\n        pass\nclass Motor(AbstractActuator):\n    def set_target(self, target):\n        return f'Motor set to {target}'",
            "pythonic": "def process_batch(items):\n    return [item.process() for item in items]", "engineering": "from abc import ABC, abstractmethod\nclass BaseDriver(ABC):\n    @abstractmethod\n    def connect(self) -> bool:\n        pass\n    @abstractmethod\n    def read_telemetry() -> dict:\n        pass",
            "m1_code": "class A:\n    def val(self): return 1\nclass B:\n    def val(self): return 2\ndef solve_m1(obj): return obj.val()", "m1_test": "assert solve_m1(A()) == 1 and solve_m1(B()) == 2",
            "m2_code": "from abc import ABC, abstractmethod\nclass Base(ABC):\n    @abstractmethod\n    def run(self): pass\nclass Sub(Base):\n    def run(self): return 'OK'\ndef solve_m2(): return Sub().run()", "m2_test": "assert solve_m2() == 'OK'",
            "m3_code": "def solve_m3(items):\n    return [x.render() for x in items]", "m3_test": "class X: render = lambda self: 'X'\nassert solve_m3([X(), X()]) == ['X', 'X']",
            "m4_code": "from abc import ABC, abstractmethod\nclass Base(ABC):\n    @abstractmethod\n    def get(self): pass\ndef solve_m4():\n    try:\n        Base()\n        return False\n    except TypeError:\n        return True", "m4_test": "assert solve_m4() is True",
            "m5_code": "class Circle:\n    def draw(self): return 'CIRCLE'\nclass Square:\n    def draw(self): return 'SQUARE'\ndef solve_m5(shape): return shape.draw()", "m5_test": "assert solve_m5(Circle()) == 'CIRCLE'",
            "h1_code": "from abc import ABC, abstractmethod\nclass Plugin(ABC):\n    @abstractmethod\n    def execute(self, data):\n        pass\nclass UpperPlugin(Plugin):\n    def execute(self, data):\n        return data.upper()\ndef solve_h1(text): return UpperPlugin().execute(text)", "h1_test": "assert solve_h1('hello') == 'HELLO'",
            "h2_code": "class Duck1:\n    def quack(self): return 'quack1'\nclass Duck2:\n    def quack(self): return 'quack2'\ndef solve_h2(ducks):\n    return [d.quack() for d in ducks]", "h2_test": "assert solve_h2([Duck1(), Duck2()]) == ['quack1', 'quack2']",
            "h3_code": "from abc import ABC, abstractmethod\nclass Calculator(ABC):\n    @abstractmethod\n    def compute(self, a, b): pass\nclass AddCalc(Calculator):\n    def compute(self, a, b): return a + b\ndef solve_h3(a, b): return AddCalc().compute(a, b)", "h3_test": "assert solve_h3(2, 3) == 5",
            "h4_code": "class BaseFormatter:\n    def format(self, val):\n        return str(val)\nclass JsonFormatter(BaseFormatter):\n    def format(self, val):\n        import json\n        return json.dumps(val)\ndef solve_h4(d): return JsonFormatter().format(d)", "h4_test": "assert solve_h4({'a': 1}) == '{\"a\": 1}'",
            "h5_code": "def solve_h5(handlers, event):\n    return [h.handle(event) for h in handlers]", "h5_test": "class H: handle = lambda self, e: e.upper()\nassert solve_h5([H()], 'e') == ['E']",
            "rob_code": "from abc import ABC, abstractmethod\nclass BaseSensor(ABC):\n    @abstractmethod\n    def read(self):\n        pass\nclass MockSensor(BaseSensor):\n    def read(self):\n        return 42.0\ndef process_telemetry(data):\n    s = MockSensor()\n    return {'reading': s.read()}", "rob_test": "assert process_telemetry([])['reading'] == 42.0"
        }
    ),
    make_topic_data(
        topic_id="6.5", title="Special / Magic Methods", module=6, module_title="Object-Oriented Programming",
        directory="05_special_magic_methods", summary="__str__, __repr__, __len__, __getitem__, __add__, and dunder protocols.",
        why_it_matters="Magic methods allow custom classes to integrate seamlessly with Python built-in operations.",
        objectives=["Implement string representations with __str__ and __repr__.", "Overload arithmetic operators.", "Implement sequence protocols with __len__ and __getitem__."],
        prerequisites=["Topic 6.4 Polymorphism"], domain="modular robotic arm", concepts=["Dunder Methods", "__str__", "__repr__", "Operator Overloading"],
        code_snippets={
            "syntax": "class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __add__(self, other):\n        return Vector(self.x + other.x, self.y + other.y)", "basic": "class Book:\n    def __init__(self, title):\n        self.title = title\n    def __str__(self):\n        return f'Book: {self.title}'",
            "intermediate": "class CustomContainer:\n    def __init__(self, items):\n        self.items = items\n    def __len__(self):\n        return len(self.items)\n    def __getitem__(self, idx):\n        return self.items[idx]", "advanced": "class CallableObj:\n    def __call__(self, x):\n        return x * 2",
            "walkthrough": "class Pose:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __repr__(self):\n        return f'Pose({self.x}, {self.y})'\n    def __eq__(self, other):\n        return isinstance(other, Pose) and (self.x, self.y) == (other.x, other.y)",
            "pythonic": "class CounterObj:\n    def __init__(self, count):\n        self.count = count\n    def __bool__(self):\n        return self.count > 0", "engineering": "class Vector3D:\n    def __init__(self, x=0.0, y=0.0, z=0.0):\n        self.x, self.y, self.z = x, y, z\n    def __add__(self, other):\n        return Vector3D(self.x + other.x, self.y + other.y, self.z + other.z)\n    def __repr__(self):\n        return f'Vector3D({self.x:.1f}, {self.y:.1f}, {self.z:.1f})'",
            "m1_code": "class Person:\n    def __init__(self, name):\n        self.name = name\n    def __str__(self):\n        return self.name\ndef solve_m1(name): return str(Person(name))", "m1_test": "assert solve_m1('Alex') == 'Alex'",
            "m2_code": "class Box:\n    def __init__(self, items):\n        self.items = items\n    def __len__(self):\n        return len(self.items)\ndef solve_m2(items): return len(Box(items))", "m2_test": "assert solve_m2([1, 2]) == 2",
            "m3_code": "class Seq:\n    def __init__(self, items):\n        self.items = items\n    def __getitem__(self, i):\n        return self.items[i]\ndef solve_m3(items, i): return Seq(items)[i]", "m3_test": "assert solve_m3([10, 20], 1) == 20",
            "m4_code": "class Num:\n    def __init__(self, v):\n        self.v = v\n    def __add__(self, other):\n        return Num(self.v + other.v)\ndef solve_m4(a, b): return (Num(a) + Num(b)).v", "m4_test": "assert solve_m4(2, 3) == 5",
            "m5_code": "class CallableFn:\n    def __call__(self, x):\n        return x * 10\ndef solve_m5(x): return CallableFn()(x)", "m5_test": "assert solve_m5(5) == 50",
            "h1_code": "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __eq__(self, other):\n        return isinstance(other, Point) and (self.x, self.y) == (other.x, other.y)\ndef solve_h1(p1, p2): return Point(*p1) == Point(*p2)", "h1_test": "assert solve_h1((1, 2), (1, 2)) is True",
            "h2_code": "class Vector:\n    def __init__(self, x, y):\n        self.x, self.y = x, y\n    def __repr__(self):\n        return f'Vector({self.x}, {self.y})'\ndef solve_h2(x, y): return repr(Vector(x, y))", "h2_test": "assert solve_h2(1, 2) == 'Vector(1, 2)'",
            "h3_code": "class SmartList:\n    def __init__(self, items):\n        self.items = items\n    def __contains__(self, item):\n        return item in self.items\ndef solve_h3(lst, target): return target in SmartList(lst)", "h3_test": "assert solve_h3([1, 2], 1) is True",
            "h4_code": "class Multiplier:\n    def __init__(self, factor):\n        self.factor = factor\n    def __mul__(self, other):\n        return self.factor * other\ndef solve_h4(f, val): return Multiplier(f) * val", "h4_test": "assert solve_h4(3, 4) == 12",
            "h5_code": "class ContextObj:\n    def __enter__(self):\n        return 'ENTERED'\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        pass\ndef solve_h5():\n    with ContextObj() as res:\n        return res", "h5_test": "assert solve_h5() == 'ENTERED'",
            "rob_code": "class TelemetryPacket:\n    def __init__(self, frame_id):\n        self.frame_id = frame_id\n    def __str__(self):\n        return f'FRAME_{self.frame_id}'\ndef process_telemetry(data):\n    p = TelemetryPacket(len(data))\n    return {'frame': str(p)}", "rob_test": "assert process_telemetry([1, 2])['frame'] == 'FRAME_2'"
        }
    ),
    make_topic_data(
        topic_id="6.6", title="Class Methods, Static Methods, and Properties", module=6, module_title="Object-Oriented Programming",
        directory="06_class_static_methods_properties", summary="@classmethod, @staticmethod, and @property decorators.",
        why_it_matters="Properties and class methods offer clean factory constructors and attribute encapsulation.",
        objectives=["Create factory constructors with @classmethod.", "Define utility functions with @staticmethod.", "Manage getters/setters with @property."],
        prerequisites=["Topic 6.5 Magic Methods"], domain="modular robotic arm", concepts=["classmethod", "staticmethod", "property"],
        code_snippets={
            "syntax": "class Demo:\n    @classmethod\n    def factory(cls):\n        return cls()\n    @staticmethod\n    def util():\n        return True\n    @property\n    def val(self):\n        return 1", "basic": "class Temperature:\n    def __init__(self, celsius):\n        self._celsius = celsius\n    @property\n    def fahrenheit(self):\n        return self._celsius * 9/5 + 32",
            "intermediate": "class Config:\n    def __init__(self, host, port):\n        self.host, self.port = host, port\n    @classmethod\n    def from_str(cls, conn_str):\n        host, port = conn_str.split(':')\n        return cls(host, int(port))", "advanced": "class MathUtil:\n    @staticmethod\n    def add(a, b):\n        return a + b",
            "walkthrough": "class RobotConfig:\n    def __init__(self, name, speed):\n        self.name = name\n        self._speed = speed\n    @property\n    def speed(self):\n        return self._speed\n    @speed.setter\n    def speed(self, val):\n        if val >= 0:\n            self._speed = val\n    @classmethod\n    def create_default(cls):\n        return cls('ROBO-X', 1.0)",
            "pythonic": "class Circle:\n    def __init__(self, radius):\n        self.radius = radius\n    @property\n    def area(self):\n        import math\n        return math.pi * self.radius**2", "engineering": "class Battery:\n    def __init__(self, capacity_wh, current_wh):\n        self._capacity = capacity_wh\n        self._current = current_wh\n    @property\n    def percentage(self):\n        return (self._current / self._capacity) * 100.0\n    @staticmethod\n    def is_safe_voltage(v):\n        return 10.0 <= v <= 14.8",
            "m1_code": "class Circle:\n    def __init__(self, r):\n        self.r = r\n    @property\n    def area(self):\n        return 3.14 * self.r**2\ndef solve_m1(r): return Circle(r).area", "m1_test": "assert solve_m1(2) == 12.56",
            "m2_code": "class Person:\n    def __init__(self, name):\n        self.name = name\n    @classmethod\n    def anonymous(cls):\n        return cls('Anon')\ndef solve_m2(): return Person.anonymous().name", "m2_test": "assert solve_m2() == 'Anon'",
            "m3_code": "class Math:\n    @staticmethod\n    def is_even(n):\n        return n % 2 == 0\ndef solve_m3(n): return Math.is_even(n)", "m3_test": "assert solve_m3(4) is True",
            "m4_code": "class Bounded:\n    def __init__(self):\n        self._val = 0\n    @property\n    def val(self):\n        return self._val\n    @val.setter\n    def val(self, v):\n        if v >= 0: self._val = v\ndef solve_m4(v): b = Bounded(); b.val = v; return b.val", "m4_test": "assert solve_m4(10) == 10 and solve_m4(-5) == 0",
            "m5_code": "class Item:\n    count = 0\n    def __init__(self):\n        Item.count += 1\n    @classmethod\n    def get_count(cls):\n        return cls.count\ndef solve_m5(): Item(); Item(); return Item.get_count()", "m5_test": "assert solve_m5() >= 2",
            "h1_code": "class Date:\n    def __init__(self, y, m, d):\n        self.y, self.m, self.d = y, m, d\n    @classmethod\n    def from_string(cls, date_str):\n        y, m, d = map(int, date_str.split('-'))\n        return cls(y, m, d)\ndef solve_h1(s): d = Date.from_string(s); return d.y, d.m, d.d", "h1_test": "assert solve_h1('2026-10-03') == (2026, 10, 3)",
            "h2_code": "class Celsius:\n    def __init__(self, temp=0):\n        self._temp = temp\n    @property\n    def temp(self):\n        return self._temp\n    @temp.setter\n    def temp(self, val):\n        if val < -273.15:\n            raise ValueError('Below absolute zero')\n        self._temp = val\ndef solve_h2(t): c = Celsius(); c.temp = t; return c.temp", "h2_test": "assert solve_h2(25) == 25",
            "h3_code": "class Validator:\n    @staticmethod\n    def is_valid_email(s):\n        return '@' in s and '.' in s\ndef solve_h3(email): return Validator.is_valid_email(email)", "h3_test": "assert solve_h3('test@test.com') is True",
            "h4_code": "class Registry:\n    _instances = []\n    def __init__(self, name):\n        self.name = name\n        Registry._instances.append(self)\n    @classmethod\n    def get_all(cls):\n        return [i.name for i in cls._instances]\ndef solve_h4(): Registry('r1'); return Registry.get_all()", "h4_test": "assert 'r1' in solve_h4()",
            "h5_code": "class Cache:\n    _hits = 0\n    @staticmethod\n    def record(): Cache._hits += 1\n    @classmethod\n    def hits(cls): return cls._hits\ndef solve_h5(): Cache.record(); return Cache.hits()", "h5_test": "assert solve_h5() >= 1",
            "rob_code": "class TelemetryStream:\n    def __init__(self, data):\n        self._data = data\n    @property\n    def size(self):\n        return len(self._data)\n    @staticmethod\n    def is_valid(d):\n        return bool(d)\ndef process_telemetry(data):\n    ts = TelemetryStream(data)\n    return {'size': ts.size, 'valid': TelemetryStream.is_valid(data)}", "rob_test": "assert process_telemetry([1])['size'] == 1"
        }
    ),
    make_topic_data(
        topic_id="6.7", title="Composition vs Inheritance", module=6, module_title="Object-Oriented Programming",
        directory="07_composition_vs_inheritance", summary="HAS-A vs IS-A relationships and object composition patterns.",
        why_it_matters="Favoring composition over inheritance produces loosely coupled, flexible designs.",
        objectives=["Distinguish IS-A vs HAS-A relationships.", "Compose complex objects from smaller components.", "Refactor deep inheritance hierarchies into composed designs."],
        prerequisites=["Topic 6.6 Class/Static Methods"], domain="modular robotic arm", concepts=["Composition", "Inheritance", "HAS-A", "IS-A"],
        code_snippets={
            "syntax": "class Engine:\n    pass\nclass Car:\n    def __init__(self):\n        self.engine = Engine()", "basic": "class Battery:\n    def charge(self): return 'CHARGED'\nclass Robot:\n    def __init__(self):\n        self.battery = Battery()",
            "intermediate": "class Motor:\n    def drive(self): return 'DRIVING'\nclass Wheel:\n    def __init__(self):\n        self.motor = Motor()\n    def spin(self): return self.motor.drive()", "advanced": "class Sensor:\n    def read(self): return 10\nclass RobotSystem:\n    def __init__(self, sensors):\n        self.sensors = sensors\n    def read_all(self):\n        return [s.read() for s in self.sensors]",
            "walkthrough": "class GPS:\n    def get_pos(self):\n        return (0.0, 0.0)\nclass Rover:\n    def __init__(self):\n        self.gps = GPS()\n    def locate(self):\n        return self.gps.get_pos()",
            "pythonic": "class Delegation:\n    def __init__(self, delegate):\n        self._delegate = delegate\n    def __getattr__(self, name):\n        return getattr(self._delegate, name)", "engineering": "class JointController:\n    def __init__(self, joint_id):\n        self.id = joint_id\n    def move(self, angle): return True\nclass RoboticArm:\n    def __init__(self, joint_ids):\n        self.joints = [JointController(jid) for jid in joint_ids]\n    def move_all(self, angle):\n        return [j.move(angle) for j in self.joints]",
            "m1_code": "class Engine:\n    def start(self): return 'RUNNING'\nclass Car:\n    def __init__(self):\n        self.engine = Engine()\ndef solve_m1(): return Car().engine.start()", "m1_test": "assert solve_m1() == 'RUNNING'",
            "m2_code": "class CPU: pass\nclass RAM: pass\nclass Computer:\n    def __init__(self):\n        self.cpu = CPU()\n        self.ram = RAM()\ndef solve_m2(): c = Computer(); return isinstance(c.cpu, CPU) and isinstance(c.ram, RAM)", "m2_test": "assert solve_m2() is True",
            "m3_code": "class Speaker:\n    def sound(self): return 'BEEP'\nclass Alarm:\n    def __init__(self):\n        self.speaker = Speaker()\n    def trigger(self): return self.speaker.sound()\ndef solve_m3(): return Alarm().trigger()", "m3_test": "assert solve_m3() == 'BEEP'",
            "m4_code": "class Component:\n    def name(self): return 'COMP'\nclass System:\n    def __init__(self, comps):\n        self.comps = comps\ndef solve_m4(): sys = System([Component(), Component()]); return len(sys.comps)", "m4_test": "assert solve_m4() == 2",
            "m5_code": "class Logger:\n    def log(self, m): return f'LOG: {m}'\nclass Service:\n    def __init__(self):\n        self.logger = Logger()\n    def run(self): return self.logger.log('OK')\ndef solve_m5(): return Service().run()", "m5_test": "assert solve_m5() == 'LOG: OK'",
            "h1_code": "class Sensor:\n    def __init__(self, name): self.name = name\n    def read(self): return 42.0\nclass Robot:\n    def __init__(self, names):\n        self.sensors = [Sensor(n) for n in names]\n    def poll(self): return {s.name: s.read() for s in self.sensors}\ndef solve_h1(): r = Robot(['s1', 's2']); return r.poll()", "h1_test": "assert solve_h1() == {'s1': 42.0, 's2': 42.0}",
            "h2_code": "class Storage:\n    def save(self, data): return f'SAVED: {data}'\nclass Pipeline:\n    def __init__(self, storage):\n        self.storage = storage\n    def execute(self, data):\n        return self.storage.save(data.upper())\ndef solve_h2(): return Pipeline(Storage()).execute('test')", "h2_test": "assert solve_h2() == 'SAVED: TEST'",
            "h3_code": "class Validator:\n    def check(self, x): return x > 0\nclass Processor:\n    def __init__(self):\n        self.v = Validator()\n    def process(self, x):\n        return x * 2 if self.v.check(x) else None\ndef solve_h3(x): return Processor().process(x)", "h3_test": "assert solve_h3(5) == 10 and solve_h3(-1) is None",
            "h4_code": "class Formatter:\n    def fmt(self, msg): return f'[{msg}]'\nclass Dispatcher:\n    def __init__(self):\n        self.formatter = Formatter()\n    def send(self, msg):\n        return self.formatter.fmt(msg)\ndef solve_h4(m): return Dispatcher().send(m)", "h4_test": "assert solve_h4('hi') == '[hi]'",
            "h5_code": "class Battery:\n    def soc(self): return 95.0\nclass Motor:\n    def rpm(self): return 1200\nclass Vehicle:\n    def __init__(self):\n        self.battery = Battery()\n        self.motor = Motor()\n    def telemetry(self):\n        return {'soc': self.battery.soc(), 'rpm': self.motor.rpm()}\ndef solve_h5(): return Vehicle().telemetry()", "h5_test": "assert solve_h5() == {'soc': 95.0, 'rpm': 1200}",
            "rob_code": "class Sensor:\n    def read(self): return 10.0\nclass Robot:\n    def __init__(self):\n        self.s = Sensor()\n    def status(self): return {'sensor_val': self.s.read()}\ndef process_telemetry(data):\n    r = Robot()\n    return r.status()", "rob_test": "assert process_telemetry([])['sensor_val'] == 10.0"
        }
    ),
    make_topic_data(
        topic_id="6.8", title="SOLID Design Principles", module=6, module_title="Object-Oriented Programming",
        directory="08_solid_design_principles", summary="Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion in Python.",
        why_it_matters="SOLID principles guide object-oriented architecture toward maintainable, extensible code.",
        objectives=["Apply Single Responsibility Principle.", "Design Open/Closed extensible classes.", "Apply Dependency Inversion with interfaces."],
        prerequisites=["Topic 6.7 Composition vs Inheritance"], domain="modular robotic arm", concepts=["SOLID", "Design Principles", "Software Architecture"],
        code_snippets={
            "syntax": "class SingleResponsibility:\n    pass", "basic": "class Reporter:\n    def format(self, data): return str(data)\nclass Printer:\n    def print_data(self, formatted): print(formatted)",
            "intermediate": "from abc import ABC, abstractmethod\nclass DiscountStrategy(ABC):\n    @abstractmethod\n    def calculate(self, price):\n        pass", "advanced": "class DependencyInversion:\n    def __init__(self, service_interface):\n        self.service = service_interface",
            "walkthrough": "from abc import ABC, abstractmethod\nclass TelemetryWriter(ABC):\n    @abstractmethod\n    def write(self, record):\n        pass\nclass ConsoleWriter(TelemetryWriter):\n    def write(self, record):\n        return f'CONSOLE: {record}'",
            "pythonic": "def calculate_total(items, tax_calc_fn):\n    return sum(items) + tax_calc_fn(items)", "engineering": "from abc import ABC, abstractmethod\nclass AbstractMotorDriver(ABC):\n    @abstractmethod\n    def set_torque(self, torque_nm: float) -> bool:\n        pass\nclass CANMotorDriver(AbstractMotorDriver):\n    def set_torque(self, torque_nm: float) -> bool:\n        return True\nclass ArmController:\n    def __init__(self, driver: AbstractMotorDriver):\n        self.driver = driver",
            "m1_code": "class SRP_Worker:\n    def do_work(self): return 'WORK'\nclass SRP_Logger:\n    def log(self, msg): return f'LOG: {msg}'\ndef solve_m1(): return SRP_Worker().do_work(), SRP_Logger().log('ok')", "m1_test": "assert solve_m1() == ('WORK', 'LOG: ok')",
            "m2_code": "from abc import ABC, abstractmethod\nclass Ext(ABC):\n    @abstractmethod\n    def val(self): pass\nclass Sub1(Ext):\n    def val(self): return 1\ndef solve_m2(): return Sub1().val()", "m2_test": "assert solve_m2() == 1",
            "m3_code": "class Bird:\n    def fly(self): return True\nclass Ostrich(Bird):\n    def fly(self): return False\ndef solve_m3(): return Ostrich().fly()", "m3_test": "assert solve_m3() is False",
            "m4_code": "from abc import ABC, abstractmethod\nclass Reader(ABC):\n    @abstractmethod\n    def read(self): pass\nclass FileReader(Reader):\n    def read(self): return 'DATA'\ndef solve_m4(): return FileReader().read()", "m4_test": "assert solve_m4() == 'DATA'",
            "m5_code": "class HighLevel:\n    def __init__(self, dep):\n        self.dep = dep\n    def run(self): return self.dep.execute()\nclass LowLevel:\n    def execute(self): return 'EXEC'\ndef solve_m5(): return HighLevel(LowLevel()).run()", "m5_test": "assert solve_m5() == 'EXEC'",
            "h1_code": "from abc import ABC, abstractmethod\nclass Formatter(ABC):\n    @abstractmethod\n    def fmt(self, data): pass\nclass JsonFmt(Formatter):\n    def fmt(self, data): return f'{{\"data\": \"{data}\"}}'\nclass Logger:\n    def __init__(self, formatter: Formatter):\n        self.f = formatter\n    def log(self, data): return self.f.fmt(data)\ndef solve_h1(d): return Logger(JsonFmt()).log(d)", "h1_test": "assert solve_h1('test') == '{\"data\": \"test\"}'",
            "h2_code": "class Task:\n    def __init__(self, name): self.name = name\nclass TaskRepository:\n    def save(self, task): return f'SAVED_{task.name}'\ndef solve_h2(): t = Task('T1'); return TaskRepository().save(t)", "h2_test": "assert solve_h2() == 'SAVED_T1'",
            "h3_code": "from abc import ABC, abstractmethod\nclass Notifier(ABC):\n    @abstractmethod\n    def notify(self, msg): pass\nclass EmailNotifier(Notifier):\n    def notify(self, msg): return f'EMAIL: {msg}'\ndef solve_h3(m): return EmailNotifier().notify(m)", "h3_test": "assert solve_h3('hi') == 'EMAIL: hi'",
            "h4_code": "class Service:\n    def __init__(self, db):\n        self.db = db\n    def get_data(self): return self.db.query()\nclass MockDB:\n    def query(self): return ['row1']\ndef solve_h4(): return Service(MockDB()).get_data()", "h4_test": "assert solve_h4() == ['row1']",
            "h5_code": "from abc import ABC, abstractmethod\nclass Payable(ABC):\n    @abstractmethod\n    def pay(self, amt): pass\nclass CreditCard(Payable):\n    def pay(self, amt): return f'PAID_{amt}'\ndef solve_h5(amt): return CreditCard().pay(amt)", "h5_test": "assert solve_h5(100) == 'PAID_100'",
            "rob_code": "from abc import ABC, abstractmethod\nclass Controller(ABC):\n    @abstractmethod\n    def step(self): pass\nclass PIDController(Controller):\n    def step(self): return {'output': 1.0}\ndef process_telemetry(data):\n    c = PIDController()\n    return c.step()", "rob_test": "assert process_telemetry([])['output'] == 1.0"
        }
    )
]
