"""Module 2 — Control Flow and Loops (topics 2.1 - 2.5)."""

from __future__ import annotations
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from self_created_tools.topic_builder import make_topic_data

TOPICS = [
    make_topic_data(
        topic_id="2.1",
        title="Conditional Statements",
        module=2,
        module_title="Control Flow and Loops",
        directory="01_conditional_statements",
        summary="if, elif, else, nested conditions, and boolean truthiness in decision engine control logic.",
        why_it_matters="Conditionals enable software to make dynamic execution choices based on runtime state.",
        objectives=["Evaluate boolean conditions.", "Implement nested logic.", "Understand truthiness in Python."],
        prerequisites=["Module 1 Getting Started"],
        domain="agricultural field robot",
        concepts=["if/elif/else", "Truthiness", "Boolean Logic"],
        code_snippets={
            "syntax": "if speed > 10:\n    print('Fast')",
            "basic": "battery = 15\nif battery < 20:\n    action = 'charge'\nelse:\n    action = 'continue'",
            "intermediate": "val = None\nif not val:\n    val = 'default'",
            "advanced": "x = 10\nstatus = 'high' if x > 5 else 'low'",
            "walkthrough": "mode = 'AUTO'\nif mode == 'AUTO':\n    state = 'RUNNING'\nelif mode == 'MANUAL':\n    state = 'PAUSED'\nelse:\n    state = 'STOPPED'",
            "pythonic": "action = 'STOP' if obstacle_near else 'MOVE'",
            "engineering": "def eval_safety(dist_m: float) -> str:\n    if dist_m < 0.5:\n        return 'EMERGENCY_STOP'\n    elif dist_m < 2.0:\n        return 'SLOW_DOWN'\n    return 'CRUISE'",
            "m1_code": "def solve_m1(val):\n    return 'POSITIVE' if val > 0 else ('NEGATIVE' if val < 0 else 'ZERO')",
            "m1_test": "assert solve_m1(5) == 'POSITIVE' and solve_m1(0) == 'ZERO'",
            "m2_code": "def solve_m2(a, b, c):\n    return max(a, b, c)",
            "m2_test": "assert solve_m2(1, 5, 3) == 5",
            "m3_code": "def solve_m3(year):\n    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)",
            "m3_test": "assert solve_m3(2024) is True and solve_m3(1900) is False",
            "m4_code": "def solve_m4(obj):\n    return bool(obj)",
            "m4_test": "assert solve_m4([]) is False and solve_m4([1]) is True",
            "m5_code": "def solve_m5(score):\n    if score >= 90: return 'A'\n    elif score >= 80: return 'B'\n    elif score >= 70: return 'C'\n    else: return 'F'",
            "m5_test": "assert solve_m5(85) == 'B'",
            "h1_code": "def solve_h1(rule_dict, state):\n    for condition, action in rule_dict.items():\n        if eval(condition, {}, state):\n            return action\n    return 'IDLE'",
            "h1_test": "assert solve_h1({'temp > 50': 'COOL', 'temp <= 50': 'NORM'}, {'temp': 60}) == 'COOL'",
            "h2_code": "def solve_h2(sensor_dict):\n    if any(v is None for v in sensor_dict.values()):\n        return 'SENSOR_FAULT'\n    if sensor_dict.get('battery', 0) < 10:\n        return 'LOW_POWER'\n    return 'OK'",
            "h2_test": "assert solve_h2({'battery': 5}) == 'LOW_POWER'",
            "h3_code": "def solve_h3(ranges):\n    return [(r[0], r[1], 'VALID' if r[0] < r[1] else 'INVALID') for r in ranges]",
            "h3_test": "assert solve_h3([(1, 5), (5, 1)]) == [(1, 5, 'VALID'), (5, 1, 'INVALID')]",
            "h4_code": "def solve_h4(status_codes):\n    return [code for code in status_codes if 200 <= code < 300]",
            "h4_test": "assert solve_h4([200, 404, 201]) == [200, 201]",
            "h5_code": "def solve_h5(val):\n    match val:\n        case 0:\n            return 'ZERO'\n        case x if x > 0:\n            return 'POS'\n        case _:\n            return 'NEG'",
            "h5_test": "assert solve_h5(10) == 'POS'",
            "rob_code": "def process_telemetry(data):\n    dist = data[0] if data else 0.0\n    state = 'HALT' if dist < 1.0 else 'MOVE'\n    return {'state': state}",
            "rob_test": "assert process_telemetry([0.5])['state'] == 'HALT'"
        }
    ),
    make_topic_data(
        topic_id="2.2",
        title="for Loops and while Loops",
        module=2,
        module_title="Control Flow and Loops",
        directory="02_for_and_while_loops",
        summary="Iteration primitives, loop conditions, polling loops, and collection processing.",
        why_it_matters="Loops automate repeating tasks and enable continuous sensor processing.",
        objectives=["Construct for loops over sequences.", "Construct event-driven while loops.", "Avoid infinite loop bugs."],
        prerequisites=["Topic 2.1 Conditional Statements"],
        domain="agricultural field robot",
        concepts=["for loop", "while loop", "Iteration"],
        code_snippets={
            "syntax": "for i in range(5):\n    print(i)",
            "basic": "count = 0\nwhile count < 3:\n    count += 1",
            "intermediate": "items = [10, 20, 30]\ntotal = 0\nfor x in items:\n    total += x",
            "advanced": "def poll_sensor(limit=3):\n    n = 0\n    while n < limit:\n        yield n\n        n += 1",
            "walkthrough": "readings = [1.2, 1.5, 0.9]\nvalid = []\nfor r in readings:\n    if r > 1.0:\n        valid.append(r)",
            "pythonic": "total = sum(x for x in range(10))",
            "engineering": "def wait_for_ready(status_fn, timeout_cycles=10):\n    cycle = 0\n    while cycle < timeout_cycles:\n        if status_fn():\n            return True\n        cycle += 1\n    return False",
            "m1_code": "def solve_m1(n):\n    return sum(range(1, n + 1))",
            "m1_test": "assert solve_m1(10) == 55",
            "m2_code": "def solve_m2(numbers):\n    res = []\n    for x in numbers:\n        if x % 2 == 0:\n            res.append(x)\n    return res",
            "m2_test": "assert solve_m2([1, 2, 3, 4]) == [2, 4]",
            "m3_code": "def solve_m3(n):\n    prod = 1\n    while n > 1:\n        prod *= n\n        n -= 1\n    return prod",
            "m3_test": "assert solve_m3(5) == 120",
            "m4_code": "def solve_m4(text):\n    vowels = 'aeiou'\n    return sum(1 for char in text.lower() if char in vowels)",
            "m4_test": "assert solve_m4('robotics') == 3",
            "m5_code": "def solve_m5(items):\n    rev = []\n    for item in items:\n        rev.insert(0, item)\n    return rev",
            "m5_test": "assert solve_m5([1, 2, 3]) == [3, 2, 1]",
            "h1_code": "def solve_h1(n):\n    fib = [0, 1]\n    while len(fib) < n:\n        fib.append(fib[-1] + fib[-2])\n    return fib[:n]",
            "h1_test": "assert solve_h1(5) == [0, 1, 1, 2, 3]",
            "h2_code": "def solve_h2(arr):\n    run_sum = 0\n    res = []\n    for x in arr:\n        run_sum += x\n        res.append(run_sum)\n    return res",
            "h2_test": "assert solve_h2([1, 2, 3]) == [1, 3, 6]",
            "h3_code": "def solve_h3(matrix):\n    flat = []\n    for row in matrix:\n        for item in row:\n            flat.append(item)\n    return flat",
            "h3_test": "assert solve_h3([[1, 2], [3, 4]]) == [1, 2, 3, 4]",
            "h4_code": "def solve_h4(stream, target):\n    count = 0\n    idx = 0\n    while idx < len(stream):\n        if stream[idx] == target:\n            count += 1\n        idx += 1\n    return count",
            "h4_test": "assert solve_h4([1, 2, 1, 3, 1], 1) == 3",
            "h5_code": "def solve_h5(n):\n    if n < 2: return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True",
            "h5_test": "assert solve_h5(13) is True and solve_h5(12) is False",
            "rob_code": "def process_telemetry(data):\n    total_dist = 0.0\n    for d in data:\n        total_dist += d\n    return {'total_distance': total_dist}",
            "rob_test": "assert process_telemetry([1.0, 2.5, 0.5])['total_distance'] == 4.0"
        }
    ),
    make_topic_data(
        topic_id="2.3",
        title="Loop Control",
        module=2,
        module_title="Control Flow and Loops",
        directory="03_loop_control",
        summary="break, continue, pass statements, and loop-else semantics.",
        why_it_matters="Loop control constructs alter execution flow during iteration.",
        objectives=["Terminate loops early with break.", "Skip iterations with continue.", "Use loop-else correctly."],
        prerequisites=["Topic 2.2 for Loops"],
        domain="agricultural field robot",
        concepts=["break", "continue", "loop-else"],
        code_snippets={
            "syntax": "for x in range(5):\n    if x == 3:\n        break",
            "basic": "for i in range(5):\n    if i % 2 == 0:\n        continue\n    print(i)",
            "intermediate": "for x in [1, 2, 3]:\n    if x == 4:\n        break\nelse:\n    print('Not found')",
            "advanced": "def find_first(items, predicate):\n    for item in items:\n        if predicate(item):\n            return item\n    return None",
            "walkthrough": "sensors = [10, 20, -1, 30]\nfor s in sensors:\n    if s < 0:\n        print('Invalid sensor reading')\n        break",
            "pythonic": "found = next((x for x in [1, 2, 3] if x > 2), None)",
            "engineering": "def check_fleet_status(robots):\n    for r in robots:\n        if r['fault']:\n            return 'FAULT_DETECTED'\n    return 'ALL_CLEAR'",
            "m1_code": "def solve_m1(numbers):\n    for x in numbers:\n        if x < 0:\n            return x\n    return None",
            "m1_test": "assert solve_m1([1, 2, -5, 4]) == -5",
            "m2_code": "def solve_m2(numbers):\n    return [x for x in numbers if x % 2 != 0]",
            "m2_test": "assert solve_m2([1, 2, 3, 4, 5]) == [1, 3, 5]",
            "m3_code": "def solve_m3(target, lst):\n    for idx, item in enumerate(lst):\n        if item == target:\n            return idx\n    return -1",
            "m3_test": "assert solve_m3('b', ['a', 'b', 'c']) == 1",
            "m4_code": "def solve_m4(items):\n    res = []\n    for x in items:\n        if x is None:\n            break\n        res.append(x)\n    return res",
            "m4_test": "assert solve_m4([1, 2, None, 4]) == [1, 2]",
            "m5_code": "def solve_m5(lst):\n    for x in lst:\n        if x == 'STOP':\n            break\n    else:\n        return 'COMPLETED'\n    return 'INTERRUPTED'",
            "m5_test": "assert solve_m5(['RUN', 'RUN']) == 'COMPLETED'",
            "h1_code": "def solve_h1(matrix, target):\n    for r, row in enumerate(matrix):\n        for c, val in enumerate(row):\n            if val == target:\n                return (r, c)\n    return None",
            "h1_test": "assert solve_h1([[1, 2], [3, 4]], 3) == (1, 0)",
            "h2_code": "def solve_h2(values):\n    filtered = []\n    for v in values:\n        if v is None or v < 0:\n            continue\n        filtered.append(v)\n    return filtered",
            "h2_test": "assert solve_h2([10, -1, None, 20]) == [10, 20]",
            "h3_code": "def solve_h3(seq):\n    seen = set()\n    res = []\n    for x in seq:\n        if x in seen:\n            continue\n        seen.add(x)\n        res.append(x)\n    return res",
            "h3_test": "assert solve_h3([1, 2, 2, 3, 1]) == [1, 2, 3]",
            "h4_code": "def solve_h4(data, threshold):\n    count = 0\n    for x in data:\n        if x > threshold:\n            count += 1\n            if count >= 3:\n                return True\n    return False",
            "h4_test": "assert solve_h4([10, 20, 30, 40], 15) is True",
            "h5_code": "def solve_h5(stream):\n    idx = 0\n    while idx < len(stream):\n        if stream[idx] == 'HEADER':\n            idx += 1\n            payload = []\n            while idx < len(stream) and stream[idx] != 'FOOTER':\n                payload.append(stream[idx])\n                idx += 1\n            return payload\n        idx += 1\n    return []",
            "h5_test": "assert solve_h5(['IDLE', 'HEADER', 'DATA1', 'FOOTER']) == ['DATA1']",
            "rob_code": "def process_telemetry(data):\n    valid = []\n    for val in data:\n        if val < 0:\n            continue\n        valid.append(val)\n    return {'valid_readings': valid}",
            "rob_test": "assert process_telemetry([1.0, -0.5, 2.0])['valid_readings'] == [1.0, 2.0]"
        }
    ),
    make_topic_data(
        topic_id="2.4",
        title="Nested Loops and Common Patterns",
        module=2,
        module_title="Control Flow and Loops",
        directory="04_nested_loops_patterns",
        summary="Nested iteration, grid processing, matrix operations, and algorithmic loop patterns.",
        why_it_matters="Multi-dimensional data structures and grids require nested iteration patterns.",
        objectives=["Process 2D matrices and grids.", "Understand time complexity in nested loops.", "Apply accumulator patterns."],
        prerequisites=["Topic 2.3 Loop Control"],
        domain="underground inspection rover",
        concepts=["Nested Loops", "Matrices", "Accumulators"],
        code_snippets={
            "syntax": "for i in range(2):\n    for j in range(2):\n        print(i, j)",
            "basic": "grid = [[1, 2], [3, 4]]\nfor row in grid:\n    for cell in row:\n        print(cell)",
            "intermediate": "matrix = [[0]*3 for _ in range(3)]",
            "advanced": "def transpose(m):\n    return [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))]",
            "walkthrough": "grid = [[1, 0], [0, 1]]\ncount = 0\nfor row in grid:\n    for val in row:\n        if val == 1:\n            count += 1",
            "pythonic": "total = sum(cell for row in grid for cell in row)",
            "engineering": "def scan_grid(grid):\n    obstacles = []\n    for r, row in enumerate(grid):\n        for c, val in enumerate(row):\n            if val == 'X':\n                obstacles.append((r, c))\n    return obstacles",
            "m1_code": "def solve_m1(rows, cols):\n    return [[r * cols + c + 1 for c in range(cols)] for r in range(rows)]",
            "m1_test": "assert solve_m1(2, 2) == [[1, 2], [3, 4]]",
            "m2_code": "def solve_m2(matrix):\n    return sum(sum(row) for row in matrix)",
            "m2_test": "assert solve_m2([[1, 2], [3, 4]]) == 10",
            "m3_code": "def solve_m3(matrix):\n    return [matrix[i][i] for i in range(len(matrix))]",
            "m3_test": "assert solve_m3([[1, 2], [3, 4]]) == [1, 4]",
            "m4_code": "def solve_m4(matrix):\n    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]",
            "m4_test": "assert solve_m4([[1, 2], [3, 4]]) == [[1, 3], [2, 4]]",
            "m5_code": "def solve_m5(n):\n    pairs = []\n    for i in range(n):\n        for j in range(i + 1, n):\n            pairs.append((i, j))\n    return pairs",
            "m5_test": "assert solve_m5(3) == [(0, 1), (0, 2), (1, 2)]",
            "h1_code": "def solve_h1(m1, m2):\n    rows_a, cols_a = len(m1), len(m1[0])\n    rows_b, cols_b = len(m2), len(m2[0])\n    res = [[0] * cols_b for _ in range(rows_a)]\n    for i in range(rows_a):\n        for j in range(cols_b):\n            for k in range(cols_a):\n                res[i][j] += m1[i][k] * m2[k][j]\n    return res",
            "h1_test": "assert solve_h1([[1, 2]], [[3], [4]]) == [[11]]",
            "h2_code": "def solve_h2(grid):\n    rows, cols = len(grid), len(grid[0])\n    count = 0\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c] == 1:\n                count += 1\n    return count",
            "h2_test": "assert solve_h2([[1, 0], [0, 1]]) == 2",
            "h3_code": "def solve_h3(matrix):\n    return [row for row in matrix if all(x >= 0 for x in row)]",
            "h3_test": "assert solve_h3([[1, 2], [-1, 3]]) == [[1, 2]]",
            "h4_code": "def solve_h4(grid, r, c):\n    rows, cols = len(grid), len(grid[0])\n    neighbors = []\n    for dr in (-1, 0, 1):\n        for dc in (-1, 0, 1):\n            if dr == 0 and dc == 0: continue\n            nr, nc = r + dr, c + dc\n            if 0 <= nr < rows and 0 <= nc < cols:\n                neighbors.append(grid[nr][nc])\n    return neighbors",
            "h4_test": "assert len(solve_h4([[1, 2], [3, 4]], 0, 0)) == 3",
            "h5_code": "def solve_h5(matrix):\n    return [val for row in matrix for val in row]",
            "h5_test": "assert solve_h5([[1], [2, 3]]) == [1, 2, 3]",
            "rob_code": "def process_telemetry(data):\n    grid = [[1, 0], [0, 1]]\n    return {'grid_sum': sum(sum(row) for row in grid)}",
            "rob_test": "assert process_telemetry([])['grid_sum'] == 2"
        }
    ),
    make_topic_data(
        topic_id="2.5",
        title="range(), enumerate(), and zip()",
        module=2,
        module_title="Control Flow and Loops",
        directory="05_range_enumerate_zip",
        summary="Built-in iteration utilities for indexed and parallel looping.",
        why_it_matters="enumerate() and zip() eliminate manual index tracking variables.",
        objectives=["Use range() for numerical iteration.", "Use enumerate() for indexed loops.", "Use zip() for parallel iteration."],
        prerequisites=["Topic 2.4 Nested Loops"],
        domain="underground inspection rover",
        concepts=["range", "enumerate", "zip"],
        code_snippets={
            "syntax": "for i, x in enumerate(['a', 'b']):\n    print(i, x)",
            "basic": "for x, y in zip([1, 2], [3, 4]):\n    print(x + y)",
            "intermediate": "names = ['a', 'b']\nscores = [10, 20]\nd = dict(zip(names, scores))",
            "advanced": "keys = ['x', 'y']\nvals = [1.0, 2.0]\nd = {k: v for k, v in zip(keys, vals)}",
            "walkthrough": "timestamps = [0.0, 0.1, 0.2]\nvalues = [10, 12, 11]\nfor i, (t, v) in enumerate(zip(timestamps, values)):\n    print(f'Frame {i}: t={t} s, v={v}')",
            "pythonic": "indexed = list(enumerate(['x', 'y', 'z'], start=1))",
            "engineering": "def correlate_sensors(timestamps, s1_vals, s2_vals):\n    return [(t, v1, v2) for t, v1, v2 in zip(timestamps, s1_vals, s2_vals)]",
            "m1_code": "def solve_m1(start, stop, step):\n    return list(range(start, stop, step))",
            "m1_test": "assert solve_m1(0, 10, 2) == [0, 2, 4, 6, 8]",
            "m2_code": "def solve_m2(items):\n    return list(enumerate(items))",
            "m2_test": "assert solve_m2(['a', 'b']) == [(0, 'a'), (1, 'b')]",
            "m3_code": "def solve_m3(l1, l2):\n    return list(zip(l1, l2))",
            "m3_test": "assert solve_m3([1, 2], ['a', 'b']) == [(1, 'a'), (2, 'b')]",
            "m4_code": "def solve_m4(keys, values):\n    return dict(zip(keys, values))",
            "m4_test": "assert solve_m4(['a', 'b'], [1, 2]) == {'a': 1, 'b': 2}",
            "m5_code": "def solve_m5(items):\n    return [f'{i}: {x}' for i, x in enumerate(items, start=1)]",
            "m5_test": "assert solve_m5(['apple']) == ['1: apple']",
            "h1_code": "def solve_h1(l1, l2, l3):\n    return [x + y + z for x, y, z in zip(l1, l2, l3)]",
            "h1_test": "assert solve_h1([1, 2], [10, 20], [100, 200]) == [111, 222]",
            "h2_code": "def solve_h2(pairs):\n    return [list(x) for x in zip(*pairs)]",
            "h2_test": "assert solve_h2([(1, 'a'), (2, 'b')]) == [[1, 2], ['a', 'b']]",
            "h3_code": "def solve_h3(seq):\n    return [(seq[i], seq[i+1]) for i in range(len(seq) - 1)]",
            "h3_test": "assert solve_h3([1, 2, 3]) == [(1, 2), (2, 3)]",
            "h4_code": "def solve_h4(items, target):\n    return [i for i, x in enumerate(items) if x == target]",
            "h4_test": "assert solve_h4(['a', 'b', 'a'], 'a') == [0, 2]",
            "h5_code": "def solve_h5(l1, l2):\n    import itertools\n    return list(itertools.zip_longest(l1, l2, fillvalue=None))",
            "h5_test": "assert solve_h5([1], ['a', 'b']) == [(1, 'a'), (None, 'b')]",
            "rob_code": "def process_telemetry(data):\n    indices = list(range(len(data)))\n    return {'samples': list(zip(indices, data))}",
            "rob_test": "assert process_telemetry([10.0, 20.0])['samples'] == [(0, 10.0), (1, 20.0)]"
        }
    )
]
